### PR TITLE
[17830] Prepare for release v2.10.0

### PR DESCRIPTION
**Pull request by JLBuenoLopez-eProsima**
## Description

This PR:

* Updates Fast CDR dependency to the latest release v1.0.27
* Updates Fast DDS roadmap
* Update Platform and Release support

## Contributor Checklist
- [x] Commit messages follow the project guidelines. 
- [N/A] The code follows the style guidelines of this project. 
- [N/A] Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
- [N/A] Any new/modified methods have been properly documented using Doxygen. 
- [N/A] Changes are ABI compatible. 
- [N/A] Changes are API compatible. 
- [N/A] New feature has been added to the `versions.md` file (if applicable).
- [N/A] New feature has been documented/Current behavior is correctly described in the documentation. 
    
- [N/A] Applicable backports have been included in the description.

## Reviewer Checklist
- [x] The PR has a milestone assigned.
- [x] Check contributor checklist is correct.
- [N/A] Check CI results: changes do not issue any warning.
- [N/A] Check CI results: failing tests are unrelated with the changes.

### CODE REVIEW

**Comment by JLBuenoLopez-eProsima** [comment]
@richiprosima please test this (I forgot to mark the `skip-ci` label. This way the CI run is ordered again)

**Review by MRicoIE2CS — APPROVED** [review]
LGTM

**Comment by JLBuenoLopez-eProsima** [comment]
Running CI as the Fast CDR submodule has been updated

**Comment by JLBuenoLopez-eProsima** [comment]
@richiprosima please test this

**Pull request merged**
