### PR TITLE
[19770] Fix comparison in remove_from_pdp_reader_history

### PR DESCRIPTION
**Pull request by MiguelCompany**
## Description

This fixes a potential deadlock introduced by f2e5ceae8fbea0a6c9445a366faaca0b98a8ef86
Built on top of 

@Mergifyio backport 2.12.x 2.11.x 2.10.x

## Contributor Checklist
- [x] Commit messages follow the project guidelines. 
- [x] The code follows the style guidelines of this project. 
- *N/A* Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
- *N/A* Any new/modified methods have been properly documented using Doxygen. 
- [x] Changes are ABI compatible. 
- [x] Changes are API compatible. 
- *N/A* New feature has been added to the `versions.md` file (if applicable).
- *N/A* New feature has been documented/Current behavior is correctly described in the documentation. 
    
- [x] Applicable backports have been included in the description.

## Reviewer Checklist
- [ ] The PR has a milestone assigned.
- [ ] Check contributor checklist is correct.
- [ ] Check CI results: changes do not issue any warning.
- [ ] Check CI results: failing tests are unrelated with the changes.

### CODE REVIEW

**Review by Mario-DL — APPROVED** [review]
LGTM. 
Lets wait for the sanitizer results

**Review by Mario-DL — APPROVED** [review]

**Comment by MiguelCompany** [comment]
@richiprosima Please test this

**Comment by Mario-DL** [comment]
Tests failing in jenkins not related with this PR.
Github Windows Security failed tests I have seen them failing in other recent PRs ocasionally.
We would need to also investigate asan failed tests in another pr.

**Comment by Mario-DL** [comment]
Thread sanitizer passed. LGTM for me

**Comment by MiguelCompany** [comment]
@Mergifyio backport 2.12.x 2.11.x 2.10.x

**Pull request merged**
