### PR TITLE
[16328] Set FASTDDS_STATISTICS CMake option to ON

### PR DESCRIPTION
**Pull request by MRicoIE2C**
Signed-off-by: Mikel Rico <mikelrico@eprosima.com>

Set FASTDDS_STATISTICS CMake option to ON

## Contributor Checklist
- [x] Commit messages follow the project guidelines. 
- [N/A] The code follows the style guidelines of this project. 
- [N/A] Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added. 
- [N/A] Any new/modified methods have been properly documented using Doxygen. 
- [N/A] Fast DDS test suite has been run locally. 
- [N/A] Changes are ABI compatible. 
- [N/A] Changes are API compatible. 
- [N/A] Documentation builds and tests pass locally. 
- [x] New feature has been added to the `versions.md` file (if applicable).
- [N/A] New feature has been documented/Current behavior is correctly described in the documentation. 
Related documentation PR: [eProsima/Fast-DDS-docs# (PR) ](https://github.com/eProsima/Fast-DDS-docs/pull/430)

## Reviewer Checklist
- [x] Check contributor checklist is correct.
- [x] Check CI results: changes do not issue any warning.
- [x] Check CI results: failing tests are unrelated with the changes.

### CODE REVIEW

**Comment by MRicoIE2C** [comment]
@richiprosima please test this

**Comment by MiguelCompany** [comment]
@richiprosima Please test this

**Comment by EduPonz** [comment]
> BlackboxTests_DDS_PIM.DDSDiscovery.AddDiscoveryServerToList is failing consistently on all platforms

Addressed in bcb24f191

**Comment by EduPonz** [comment]
@richiprosima please test this

**Comment by MiguelCompany** [comment]
@richiprosima Please test Windows

**Comment by EduPonz** [comment]
@richiprosima please test linux

**Comment by EduPonz** [comment]
@richiprosima please test windows mac

**Review by MiguelCompany — APPROVED** [review]

**Pull request merged**
