### PR TITLE
[19023] Custom Payload pools test implementation

### PR DESCRIPTION
**Pull request by jsantiago-eProsima**
## Contributor Checklist
- [x] Commit messages follow the project guidelines. 
- [x] The code follows the style guidelines of this project. 
- [x] Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
- [x] Any new/modified methods have been properly documented using Doxygen. 
- [ ] Changes are ABI compatible. 
- [x] Changes are API compatible. 
- **N/A** New feature has been added to the `versions.md` file (if applicable).
- **N/A** New feature has been documented/Current behavior is correctly described in the documentation. 
    
- **N/A** Applicable backports have been included in the description.

## Reviewer Checklist
- [x] The PR has a milestone assigned.
- [x] Check contributor checklist is correct.
- [ ] Check CI results: changes do not issue any warning.
- [ ] Check CI results: failing tests are unrelated with the changes.

### CODE REVIEW

**Comment by JesusPoderoso** [comment]
@richiprosima please test this

**Comment by JesusPoderoso** [comment]
@richiprosima please test this

**Comment by JesusPoderoso** [comment]
@richiprosima please test this

**Comment by JesusPoderoso** [comment]
@richiprosima please test this

**Comment by jsantiago-eProsima** [comment]
@richiprosima please test mac

**Comment by jsantiago-eProsima** [comment]
@richiprosima please test mac

**Comment by jsantiago-eProsima** [comment]
@JesusPoderoso changes LGTM.

**Pull request merged**
