### PR TITLE
[18156] Participant ignore local enpoints implementation

### PR DESCRIPTION
**Pull request by EduPonz**
## Description

This PR provides the implementation for the participant ignore local endpoints tests.
Depends on:
* #3476

## Contributor Checklist
- [x] Commit messages follow the project guidelines. 
- [x] The code follows the style guidelines of this project. 
- *N/A* Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
- *N/A* Any new/modified methods have been properly documented using Doxygen. 
- [x] Changes are ABI compatible. 
- [x] Changes are API compatible. 
- *N/A* New feature has been added to the `versions.md` file (if applicable).
- [x] New feature has been documented/Current behavior is correctly described in the documentation. 
    * Related documentation PR: eProsima/Fast-DDS-docs#485
- *N/A* Applicable backports have been included in the description.

## Reviewer Checklist
- [x] The PR has a milestone assigned.
- [x] Check contributor checklist is correct.
- [x] Check CI results: changes do not issue any warning.
- [x] Check CI results: failing tests are unrelated with the changes.

### CODE REVIEW

**Comment by EduPonz** [comment]
@richiprosima please test this

**Comment by EduPonz** [comment]
@richiprosima please test this

**Comment by JesusPoderoso** [comment]
@richiprosima Please test mac

**Review by JesusPoderoso — APPROVED** [review]
LGTM

**Comment by EduPonz** [comment]
Merging to the intermediate branch, where the windows warnings will be addresses

**Pull request merged**
