### PR TITLE
Include SHM in the default transports. <master> [9727]

### PR DESCRIPTION
**Pull request by MiguelCompany**
This is a port of #1515 

Signed-off-by: Miguel Company <MiguelCompany@eprosima.com>

### CODE REVIEW

**Review by JLBuenoLopez-eProsima — COMMENTED** [review]
LGTM.

There should be an attached pull request modifying the documentation.

**Comment by richiware** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/3053/)
* Linux aarch64[Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux%20aarch64/276/)
* Mac [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/2736/)
* Windows [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/3064/)

**Review by IkerLuengo — APPROVED** [review]
LGTM.

Documentation changes ready on https://github.com/eProsima/Fast-RTPS-docs/pull/205
Relaunching tests because it looks that valgrind found errors but the info is gone.

**Comment by richiware** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/3078/)
* Linux aarch64[Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux%20aarch64/295/)
* Mac [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/2755/)
* Windows [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/3096/)

**Comment by MiguelCompany** [comment]
Unrelated failures.

**Pull request merged**
