### PR TITLE
Allow fully qualified name in TypeDescriptor [11063]

### PR DESCRIPTION
**Pull request by YangboLong**
According to the DDS-XTypes spec 7.5.2.4.10, the name of TypeDescriptor
should be the fully qualified name, which is the concatenation of
module names with the name of a type inside of those modules.

This change will allow an object of DynamicTypeBuilder to set a type
name that contains colon in it. Sometimes it's necessary to use a fully
qualified name in dynamic types to communicate to some existing
ros2 topic directly.

Related issue: https://gitmemory.com/issue/eProsima/Fast-RTPS-Gen/21/603785610

### CODE REVIEW

**Comment by YangboLong** [comment]
I just noticed that this PR https://github.com/eProsima/Fast-DDS/pull/1345 attempted to solve the same problem. Would you let me know what's wrong with my PR?

**Review by MiguelCompany — CHANGES_REQUESTED** [review]
The logic looks good to me.

Please add some unit tests [here](https://github.com/eProsima/Fast-DDS/blob/master/test/unittest/xtypes/XTypesTests.cpp)

**Comment by MiguelCompany** [comment]
> Would you let me know what's wrong with my PR?

It is just that we didn't have time to do the review. Could you please fix [DCO](https://github.com/eProsima/Fast-DDS/pull/1831/checks?check_run_id=2099569641) and [linters](http://jenkins.eprosima.com:8080/job/fastdds_github_uncrustify/2021/)?

**Comment by YangboLong** [comment]
I've added a few test cases and fixed the DCO and linters. Would you please review it again?

**Comment by MiguelCompany** [comment]
@richiprosima Please test this

**Review by MiguelCompany — APPROVED** [review]
LGTM

**Comment by MiguelCompany** [comment]
@MergifyIO backport 2.2.x 2.1.x 2.0.x

**Pull request merged**
