### PR TITLE
[19452] Fix required version in CMakeLists file in examples

### PR DESCRIPTION
**Pull request by elianalf**
## Description

This pr fixes the required version of Fast DDS in CMakeLists file in some of the examples

## Contributor Checklist

- [x] Commit messages follow the project guidelines. 
- [x] The code follows the style guidelines of this project. 
- N/a Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
- N/A Any new/modified methods have been properly documented using Doxygen. 
- N/A Any new configuration API has an equivalent XML API (with the corresponding XSD extension) 
- ❌ Changes are backport compatible: they do **NOT** break ABI nor change library core behavior. 
- ❌ Changes are API compatible. 
- N/A New feature has been added to the `versions.md` file (if applicable).
- N/A New feature has been documented/Current behavior is correctly described in the documentation. 
    
- N/A Applicable backports have been included in the description.

## Reviewer Checklist

- [x] The PR has a milestone assigned.
- [x] The title and description correctly express the PR's purpose.
- [x] Check contributor checklist is correct.
- [ ] Check CI results: changes do not issue any warning.
- [ ] Check CI results: failing tests are unrelated with the changes.

### CODE REVIEW

**Review by JesusPoderoso — APPROVED** [review]
LGTM (they are getting deleted really soon)

**Comment by elianalf** [comment]
@richiprosima please test linux

**Comment by elianalf** [comment]
@richiprosima please test linux

**Comment by elianalf** [comment]
@mergify 2.13.x

**Comment by elianalf** [comment]
https://github.com/Mergifyio backport 2.13.x

**Comment by elianalf** [comment]
@richiprosima test it

**Pull request closed without merging**
