### PR TITLE
[14681] Fixing WriterProxyData clear() method

### PR DESCRIPTION
**Pull request by MiguelBarro**
Signed-off-by: Miguel Barro <miguelbarro@eprosima.com>

## Description

The use of common proxy pools in the EDP management was generating issues due to the improper clean up of the proxies.

## Contributor Checklist
- [x] Commit messages follow the project guidelines. 
- [x] The code follows the style guidelines of this project. 
- [ ]NA Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added. 
- [ ] Any new/modified methods have been properly documented using Doxygen. 
- [x] Fast DDS test suite has been run locally. 
- [x] Changes are ABI compatible. 
- [x] Changes are API compatible. 
- [ ] Documentation builds and tests pass locally. 
- [ ] New feature has been added to the `versions.md` file (if applicable).
- [ ] New feature has been documented/Current behavior is correctly described in the documentation. 

## Reviewer Checklist
- [ ] Check contributor checklist is correct.
- [ ] Check CI results: changes do not issue any warning.
- [ ] Check CI results: failing tests are unrelated with the changes.

### CODE REVIEW

**Review by jsantiago-eProsima — APPROVED** [review]
LGTM

**Comment by MiguelBarro** [comment]
@richiprosima Please test this for me 👀

**Review by MiguelCompany — APPROVED** [review]
LGTM

**Comment by MiguelCompany** [comment]
@mergifyio backport 2.6.x 2.3.x 2.1.x

**Pull request merged**
