### PR TITLE
[17976] Correctly assign multicast port to multicast initial peers

### PR DESCRIPTION
**Pull request by MiguelCompany**
## Description

This PR fixes a wrong behavior where a multicast address on an initial peer locator is being incorrectly treated as unicast.

@Mergifyio backport 2.9.x 2.6.x 2.1.x

## Contributor Checklist
- [x] Commit messages follow the project guidelines. 
- [x] The code follows the style guidelines of this project. 
- [x] Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
- **N/A** Any new/modified methods have been properly documented using Doxygen. 
- [x] Changes are ABI compatible. 
- [x] Changes are API compatible. 
- **N/A** New feature has been added to the `versions.md` file (if applicable).
- **N/A** New feature has been documented/Current behavior is correctly described in the documentation. 
    
- [x] Applicable backports have been included in the description.

## Reviewer Checklist
- [x] The PR has a milestone assigned.
- [x] Check contributor checklist is correct.
- [x] Check CI results: changes do not issue any warning.
- [x] Check CI results: failing tests are unrelated with the changes.

### CODE REVIEW

**Comment by MRicoIE2CS** [comment]
@richiprosima please test this

**Review by MRicoIE2CS — CHANGES_REQUESTED** [review]
I have tried and run the new test without the commit that adds the fix, and the test passes.
Please check that the test thoroughly checks the tracked bug.

**Comment by MRicoIE2CS** [comment]
@richiprosima please test this

**Review by MRicoIE2CS — APPROVED** [review]
LGTM with green CI

**Comment by MiguelCompany** [comment]
@Mergifyio backport 2.9.x 2.6.x 2.1.x

**Pull request merged**
