### PR TITLE
[13259] Content filter implementation

### PR DESCRIPTION
**Pull request by MiguelCompany**
This PR adds reader-side content-filter implementation.

Co-Authored-By: Tomoya Fujita <Tomoya.Fujita@sony.com>

### CODE REVIEW

**Comment by MiguelCompany** [comment]
@fujitatomoya @iuhilnehc-ynos FYI. This is the final PR to bring content filter into the master branch.

**Review by JLBuenoLopez-eProsima — APPROVED** [review]
LGTM with green CI

**Comment by MiguelCompany** [comment]
@richiprosima Please test mac

**Review by JLBuenoLopez-eProsima — APPROVED** [review]
LGTM

**Pull request merged**
