### PR TITLE
Fix recurrent minor data races from tests [16344]

### PR DESCRIPTION
**Pull request by juanlofer-eprosima**
## Description

This PR removes various data races frequently arising in tests, which are mostly due to their implementation (not library's).

## Contributor Checklist
- [x] Commit messages follow the project guidelines. 
- [x] The code follows the style guidelines of this project. 
- **N/A** Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added. 
- **N/A** Any new/modified methods have been properly documented using Doxygen. 
- [x] Fast DDS test suite has been run locally. 
- [x] Changes are ABI compatible. 
- [x] Changes are API compatible. 
- [x] Documentation builds and tests pass locally. 
- **N/A** New feature has been added to the `versions.md` file (if applicable).
- **N/A** New feature has been documented/Current behavior is correctly described in the documentation. 

## Reviewer Checklist
- [ ] Check contributor checklist is correct.
- [ ] Check CI results: changes do not issue any warning.
- [ ] Check CI results: failing tests are unrelated with the changes.

### CODE REVIEW

**Review by EduPonz — CHANGES_REQUESTED** [review]
The logic of the changes LGTM, however:
1. There are compilation warnings in Windows
2. I think all the un-checked boxes in the checklist can be set to `*N/A*`

**Comment by juanlofer-eprosima** [comment]
@richiprosima Please test windows

**Review by EduPonz — DISMISSED** [review]

**Comment by EduPonz** [comment]
@richiprosima please test mac

**Comment by juanlofer-eprosima** [comment]
@richiprosima Please test this

**Comment by juanlofer-eprosima** [comment]
@richiprosima Please test this

**Review by MiguelCompany — APPROVED** [review]

**Pull request merged**
