### PR TITLE
Fix for put_time on CentOS 7

### LINKED ISSUE #494: Fast-RTPS Fails to Compile on CentOS 7
It looks like Fast-RTPS fails to compile on CentOS 7 due to a call to `std::put_time()` inside `src/cpp/log/Log.cpp`. This is because `put_time` wasn't implemented until Gcc 5.0 according to [this bug](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=54354#c9). Unfortunately, CentOS 7 ships w/ Gcc 4.8.5 and upgrading may not be an option for all users.

I realize that `put_time` is part of C++-11, however, CentOS / RHEL are very popular OS's that may be worth supporting. Is there any chance there is an alternative implementation that you will accept to get around this issue?

This particular method appears to be pretty innocuous. I will take a look at an alternative implementation and open a PR. Thanks

### PR DESCRIPTION
**Pull request by jml1795**
This should fix #494 but is mostly provided as an example workaround. Not sure this is the implementation you will want to use. Hope this helps

### CODE REVIEW

**Comment by richiware** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/1548/)
* Mac [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/1511/)
* Windows [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/1522/)

**Comment by jml1795** [comment]
@richiware I force pushed a fix for the extra `<<` (the cause of the failed CI job). I see `2b47e... into a8691...` in the logs which is the commit I force-pushed over. Can you rerun manually?

Unfortunately, I also hit a snag w/ an include of `codecvt`, which also wasn't implemented in the version of gcc that ships w/ CentOS 7. I am working on a patch that uses boost if so configured, but not sure if this is desirable for upstream. Let me know if you would like it. Similar to [this](https://github.com/bakwc/JamSpell/pull/13/files)

**Comment by richiware** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/1549/)
* Mac [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/1512/)
* Windows [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/1523/)

**Comment by richiware** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/1557/)
* Mac [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/1520/)
* Windows [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/1531/)

**Pull request closed without merging**
