### PR TITLE
[20648] Only run PRs CI when run-ci label is added

### PR DESCRIPTION
**Pull request by EduPonz**
## Description

This PR changes the way Github CI is managed. From now on, to run CI, a label `run-ci` needs to be added to the PR. Once the CI starts, that label is removed and `ci-pending` one is added.

@Mergifyio backport 2.13.x 2.10.x 2.6.x

This PR depends on:
* eProsima/eProsima-CI#80

## Contributor Checklist
- [x] Commit messages follow the project guidelines. 
- _N/A_: The code follows the style guidelines of this project. 
- _N/A_: Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
- _N/A_: Any new/modified methods have been properly documented using Doxygen. 
- _N/A_: Changes are ABI compatible. 
- _N/A_: Changes are API compatible. 
- _N/A_: New feature has been added to the `versions.md` file (if applicable).
- _N/A_: New feature has been documented/Current behavior is correctly described in the documentation. 
    
- [x] Applicable backports have been included in the description.

## Reviewer Checklist

- [x] The PR has a milestone assigned.
- [x] The title and description correctly express the PR's purpose.
- [x] Check contributor checklist is correct.
- [x] Check CI results: changes do not issue any warning.
- [x] Check CI results: failing tests are unrelated with the changes.

### CODE REVIEW

**Review by JesusPoderoso — APPROVED** [review]
LGTM! 🚀

**Review by JesusPoderoso — APPROVED** [review]

**Comment by JesusPoderoso** [comment]
@Mergifyio backport 2.13.x 2.10.x 2.6.x

**Review by JesusPoderoso — APPROVED** [review]
LGTM

**Comment by EduPonz** [comment]
Last commit only changed the trigger, which @JesusPoderoso tested. Since CI had run on the previous commit, I've cancelled CI and I'm merging this.

**Pull request merged**
