### PR TITLE
[19089] Fix HelloWorld DataSharing example idl

### PR DESCRIPTION
**Pull request by JesusPoderoso**
## Description

One of the Data-sharing constraints is that the types must be bounded. In the Data-sharing helloworld example, it is forced to use datasharing but the IDL types do not use bounded strings. 
This Pull Request updates IDL to use bounded string, and regenerates the types with the bounded string.

@Mergifyio backport 2.11.x 2.10.x 2.6.x 

Fixes #3710 

## Contributor Checklist
- [x] Commit messages follow the project guidelines. 
- [x] The code follows the style guidelines of this project. 
- **N/A** Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
- **N/A** Any new/modified methods have been properly documented using Doxygen. 
- **N/A** Changes are ABI compatible. 
- **N/A** Changes are API compatible. 
- **N/A** New feature has been added to the `versions.md` file (if applicable).
- **N/A** New feature has been documented/Current behavior is correctly described in the documentation. 
    
- [x] Applicable backports have been included in the description.

## Reviewer Checklist
- [x] The PR has a milestone assigned.
- [ ] Check contributor checklist is correct.
- [x] Check CI results: changes do not issue any warning.
- [x] Check CI results: failing tests are unrelated with the changes.

### CODE REVIEW

**Comment by Mario-DL** [comment]
Changes LGTM. I was wondering if the changes should be backported, in that case, the types should be re-generated with the corresponding fastddsgen version, what do you think @EduPonz ?. Also, if backporting is considered, it should be 2.11.x, 2.10.x and 2.6.x

**Comment by JLBuenoLopez-eProsima** [comment]
> Changes LGTM. I was wondering if the changes should be backported, in that case, the types should be re-generated with the corresponding fastddsgen version, what do you think @EduPonz ?. Also, if backporting is considered, it should be 2.11.x, 2.10.x and 2.6.x

I think this should be backported and the types should be regenerated as suggested by Mario.

**Comment by JesusPoderoso** [comment]
@Mergifyio backport 2.11.x 2.10.x 2.6.x

**Comment by Mario-DL** [comment]
@richiprosima please test this

**Comment by JesusPoderoso** [comment]
@richiprosima please test this

**Comment by JesusPoderoso** [comment]
@richiprosima please test this

**Comment by JesusPoderoso** [comment]
@richiprosima please test this

**Comment by Mario-DL** [comment]
@richiprosima please test this

**Comment by JesusPoderoso** [comment]
@richiprosima please test this

**Review by EduPonz — DISMISSED** [review]

**Review by Mario-DL — APPROVED** [review]
LGTM

**Pull request merged**
