### PR TITLE
Fix WLP deadlock and EDP discovery performance improvement [14450][14457]

### PR DESCRIPTION
**Pull request by EduPonz**
## Contributor Checklist
- [x] Commit messages follow the project guidelines. 
- [x] The code follows the style guidelines of this project. 
- [ ] Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added. 
- [ ] Any new/modified methods have been properly documented using Doxygen. 
- [ ] Fast DDS test suite has been run locally. 
- [x] Changes are ABI compatible. 
- [x] Changes are API compatible. 
- [ ] Documentation builds and tests pass locally. 
- [ ] New feature has been added to the `versions.md` file (if applicable).
- [ ] New feature has been documented/Current behavior is correctly described in the documentation. 

## Reviewer Checklist
- [x] Check contributor checklist is correct.
- [x] Check CI results: changes do not issue any warning.
- [x] Check CI results: failing tests are unrelated with the changes.

### CODE REVIEW

**Review by JLBuenoLopez-eProsima — DISMISSED** [review]
LGTM! CI failures are unrelated!

**Comment by jsantiago-eProsima** [comment]
We should rebase these modifications on top of the Thread Sanitizer branch and check that the overall status of issues is the same before merging into master.

**Comment by MiguelCompany** [comment]
@MiguelBarro this one can be rebased

**Review by JLBuenoLopez-eProsima — COMMENTED** [review]
Notification to `on_writer_discovery` callback is done always with the mutex taken except in `StatefulReader::matched_writer_add`. I suggest analyzing if the mutex is required to be taken in order to call the callback or not and be consistent throughout the methods.

**Review by JLBuenoLopez-eProsima — APPROVED** [review]
LGTM though it needs to be rebased. CI failures are unrelated

**Review by JLBuenoLopez-eProsima — APPROVED** [review]
LGTM

**Pull request merged**
