### PR TITLE
[galactic] Fix: gap not being sent with heartbeat [14676]

### PR DESCRIPTION
**Pull request by hexonxons**
Signed-off-by: Aleksandr Rozhdestvenskii <hexonxons@gmail.com>

### CODE REVIEW

**Review by richiware — APPROVED** [review]

**Comment by MiguelCompany** [comment]
@richiprosima Please test this

**Comment by MiguelCompany** [comment]
This could be merged once the uncrustify job stops complaining

**Comment by richiware** [comment]
@hexonxons Our CI job for running uncrustifly failed. Could you fix it? Thanks

**Comment by hexonxons** [comment]
@richiware Done. But are you sure that is how multiline `if` should be formatted? In master branch multiline `if` formatted like it was before changes:
https://github.com/eProsima/Fast-DDS/blob/cb8b84aaaa97824158a428914597da9c46f653a8/src/cpp/rtps/writer/StatefulWriter.cpp#L717-L726

**Pull request merged**
