### PR TITLE
[18004] Added length checks to prevent nullptr memcpy calls

### PR DESCRIPTION
**Pull request by jsantiago-eProsima**
## Description

UBSan (Undefined behavior sanitizer) reports nullptr memcpy calls when memcpy arguments should be guaranteed as not null. Checks have been added to prevent this.

## Contributor Checklist
- [x] Commit messages follow the project guidelines. 
- [x] The code follows the style guidelines of this project. 
- [x] Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
- [x] Any new/modified methods have been properly documented using Doxygen. 
- [x] Changes are ABI compatible. 
- [x] Changes are API compatible. 
- [ ] New feature has been added to the `versions.md` file (if applicable).
- [ ] New feature has been documented/Current behavior is correctly described in the documentation. 
    
- [ ] Applicable backports have been included in the description.

## Reviewer Checklist
- [x] The PR has a milestone assigned.
- [ ] Check contributor checklist is correct.
- [ ] Check CI results: changes do not issue any warning.
- [ ] Check CI results: failing tests are unrelated with the changes.

### CODE REVIEW

**Comment by jsantiago-eProsima** [comment]
@richiprosima please test linux

**Comment by JLBuenoLopez-eProsima** [comment]
Can we include a regression test?

**Comment by Mario-DL** [comment]
We should make decision on whether we are finally including the test or not. Friendly pinging @jsantiago-eProsima @JLBuenoLopez-eProsima

**Comment by jsantiago-eProsima** [comment]
@richiprosima please test this

**Review by JLBuenoLopez-eProsima — APPROVED** [review]
LGTM with green CI

**Review by JLBuenoLopez-eProsima — APPROVED** [review]
LGTM with green CI

**Comment by EduPonz** [comment]
@richiprosima please test linux test mac

**Comment by EduPonz** [comment]
@richiprosima please test mac

**Pull request merged**
