### PR TITLE
[13364] Fix memory problem when ciphering payload

### LINKED ISSUE #2379: Not enough memory to cipher payload [13364]
There is an error when try to send a big message (near 64 Kb boundary). It seems that encryption overhead is not considered when packing submessages inside `RTPSMessageGroup`. Such error occurs when the encryption plugin tries to encode the message, but it is too late. All of this can lead to message retransmission or even inability to send the message at all.

## Expected Behavior
It should be possible send messages of any size. If the submessage does not fit into the buffer then it should be split into smaller chunks.

## Current Behavior
There are the following error logs:
```
2021-12-23 14:06:46.067 [SECURITY_CRYPTO Error] Not enough memory to cipher payload -> Function serialize_SecureDataBody
2021-12-23 14:06:46.067 [RTPS_WRITER Error] Error encoding rtps message. -> Function send

```
## Steps to Reproduce
1. Compile the test program (attached).
2. Copy certs directory where you want to run the program.
3. Run the reader instance: ./big_message_test
4. Run the writer instance: ./big_message_test writer

## System information
- Fast-RTPS version: 2.4.0
- OS: Ubuntu 20.04

## Additional context
There is some attempt to limit a message size in `DataMsg::addSubmessageData()`:
```
    if (size32 <= std::numeric_limits<uint16_t>::max())
    {
        submessage_size = static_cast<uint16_t>(size32);
        octet* o = reinterpret_cast<octet*>(&submessage_size);
        if (msg->msg_endian == DEFAULT_ENDIAN)
        {
            msg->buffer[submessage_size_pos] = *(o);
            msg->buffer[submessage_size_pos + 1] = *(o + 1);
        }
        else
        {
            msg->buffer[submessage_size_pos] = *(o + 1);
            msg->buffer[submessage_size_pos + 1] = *(o);
        }

        *is_big_submessage = false;
    }

```
But this code does not consider an encryption overhead and the fact that buffer size can less than a hardcoded value. Right now the buffer size is less than 65535, because of memory alignment.
Also in the function `RTPSMessageGroup::insert_submessage()`:
```
    if (!append_message(full_msg_, submessage_msg_))
    {
        // Retry
        flush_and_reset();
        add_info_dst_in_buffer(full_msg_, destination_guid_prefix);

        if (!append_message(full_msg_, submessage_msg_))
        {
            logError(RTPS_WRITER, "Cannot add RTPS submesage to the CDRMessage. Buffer too small");
            return false;
        }
    }

```
[big_message_test.zip](https://github.com/eProsima/Fast-DDS/files/7769261/big_message_test.zip)

### PR DESCRIPTION
**Pull request by JLBuenoLopez-eProsima**
This closes #2379

### CODE REVIEW

**Comment by JLBuenoLopez-eProsima** [comment]
This PR breaks several security tests:

* Communication tests in several platforms
* Blackbox tests in Windows platform

**Review by richiware — CHANGES_REQUESTED** [review]
After a meeting we decided this approach is not the better one. The calculation has to be done when the `CacheChange_t` is added in the `WriterHistory`, as it is done now. According to @MiguelCompany  we have to take into account the size of the DataFrag header when calculating the size of each fragment.

**Comment by MiguelCompany** [comment]
@richiware This has been rebased, and I have changed the last commit (the one that fixes the issue), with a nicer solution.

Would you mind reviewing this?

**Comment by EduPonz** [comment]
@mergifyio rebase

**Comment by EduPonz** [comment]
@richiprosima please test this

**Comment by MiguelCompany** [comment]
@mergifyio rebase

**Comment by MiguelCompany** [comment]
@richiprosima please test mac

**Comment by MiguelCompany** [comment]
@richiprosima Please test this

**Review by EduPonz — APPROVED** [review]

**Comment by EduPonz** [comment]
@richiprosima please test windows test mac

**Comment by EduPonz** [comment]
@richiprosima please test windows

**Comment by EduPonz** [comment]
@richiprosima please test windows

**Comment by EduPonz** [comment]
@MiguelCompany do we need to backport this?

**Comment by MiguelCompany** [comment]
@mergifyio backport 2.12.x 2.11.x 2.10.x 2.6.x

**Pull request merged**
