### PR TITLE
[19638] Fix clang warnings

### PR DESCRIPTION
**Pull request by JLBuenoLopez-eProsima**
## Description

This PR cherry-picks 9c76dcc4490bea2204886120ba12ed5923e662b9 into 2.11.x. This PR should be merged first into the branch before considering merging any other backport. MacOs CI is broken due to the warnings fixed in this PR.

@Mergifyio backport 2.10.x 2.6.x.

## Contributor Checklist
- [N/A] Commit messages follow the project guidelines. 
- [x] The code follows the style guidelines of this project. 
- [N/A] Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
- [N/A] Any new/modified methods have been properly documented using Doxygen. 
- [x] Changes are ABI compatible. 
- [N/A] Changes are API compatible. 
- [N/A] New feature has been added to the `versions.md` file (if applicable).
- [N/A] New feature has been documented/Current behavior is correctly described in the documentation. 
    
- [x] Applicable backports have been included in the description.

## Reviewer Checklist
- [x] The PR has a milestone assigned.
- [x] Check contributor checklist is correct.
- [ ] Check CI results: changes do not issue any warning.
- [ ] Check CI results: failing tests are unrelated with the changes.

### CODE REVIEW

**Comment by JLBuenoLopez-eProsima** [comment]
@Mergifyio backport 2.10.x 2.6.x

**Comment by JLBuenoLopez-eProsima** [comment]
@richiprosima please test this

**Comment by MiguelCompany** [comment]
@richiprosima Please test mac

**Comment by JLBuenoLopez-eProsima** [comment]
The specific test that have failed in MacOs is not modified in this PR. Nevertheless, it seems like its failing consistently with the same error. The warnings are fixed by this PR.

**Review by MiguelCompany — APPROVED** [review]

**Pull request merged**
