### PR TITLE
Fix out of scope variable call in Persistence service [15995]

### PR DESCRIPTION
**Pull request by jparisu**
Signed-off-by: jparisu <javierparis@eprosima.com>

## Description

A variable was being created under an scope and its reference used out from that scope in Persistence Service.

## Contributor Checklist
- [x] Commit messages follow the project guidelines. 
- [x] The code follows the style guidelines of this project. 
- [ ] Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added. 
- [ ] Any new/modified methods have been properly documented using Doxygen. 
- [ ] Fast DDS test suite has been run locally. 
- [x] Changes are ABI compatible. 
- [x] Changes are API compatible. 
- [ ] Documentation builds and tests pass locally. 
- [ ] New feature has been added to the `versions.md` file (if applicable).
- [ ] New feature has been documented/Current behavior is correctly described in the documentation. 

## Reviewer Checklist
- [ ] Check contributor checklist is correct.
- [ ] Check CI results: changes do not issue any warning.
- [ ] Check CI results: failing tests are unrelated with the changes.

### CODE REVIEW

**Review by rsanchez15 — APPROVED** [review]
Double check [mac CI results]
(http://jenkins.eprosima.com:8080/job/fastdds_mac/2699/#showFailuresLink)

**Comment by JLBuenoLopez-eProsima** [comment]
@richiprosima Please test mac

**Comment by JLBuenoLopez-eProsima** [comment]
@richiprosima please test mac again

**Review by JLBuenoLopez-eProsima — APPROVED** [review]
:+1:

**Pull request merged**
