### PR TITLE
Change internal include path of nlohmann/json header file

### PR DESCRIPTION
**Pull request by rsanchez15**
## Contributor Checklist
- [x] Commit messages follow the project guidelines. 
- [x] The code follows the style guidelines of this project. 
- [ ] Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added. 
- [ ] Any new/modified methods have been properly documented using Doxygen. 
- [ ] Fast DDS test suite has been run locally. 
- [x] Changes are ABI compatible. 
- [x] Changes are API compatible. 
- [ ] Documentation builds and tests pass locally. 
- [ ] New feature has been added to the `versions.md` file (if applicable).
- [ ] New feature has been documented/Current behavior is correctly described in the documentation. 

## Reviewer Checklist
- [ ] Check contributor checklist is correct.
- [ ] Check CI results: changes do not issue any warning.
- [ ] Check CI results: failing tests are unrelated with the changes.

### CODE REVIEW

**Comment by JLBuenoLopez-eProsima** [comment]
@rsanchez15, CI is failing to build Fast DDS both in Linux and in Windows (Mac failed before trying to build, cloning the repositories). Please, take a look

**Comment by rsanchez15** [comment]
> @rsanchez15, CI is failing to build Fast DDS both in Linux and in Windows (Mac failed before trying to build, cloning the repositories). Please, take a look

Commit [cfc6c87](https://github.com/eProsima/Fast-DDS/pull/2808/commits/cfc6c87c4e7c0628606bc8e5e8f2f125dda8707e) should fix this

**Comment by rsanchez15** [comment]
@richiprosima Please test this

**Comment by EduPonz** [comment]
@richiprosima please test this

**Review by EduPonz — APPROVED** [review]

**Pull request merged**
