### PR TITLE
Garbage collect remote SHM segments when origin Participant is closed… > 2.0.x [9029]

### PR DESCRIPTION
**Pull request by LuisGP**
Backport #1250 to 2.0.x

### CODE REVIEW

**Review by MiguelBarro — DISMISSED** [review]
LGTM

**Comment by richiware** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/2459/)
* Mac [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/2261/)
* Windows [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/2447/)

**Review by MiguelCompany — APPROVED** [review]
Just rebased to resolve conflicts and force new CI

**Comment by richiware** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/2539/)
* Mac [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/2350/)
* Windows [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/2546/)

**Pull request merged**
