### PR TITLE
fix:  liveliness core dump caused by omit mutex lock

### PR DESCRIPTION
**Pull request by dameidu**
fix:  liveliness core dump caused by omit mutex lock

## Contributor Checklist
- [ ] Commit messages follow the project guidelines. 
- [x] The code follows the style guidelines of this project. 
- [ ] Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added. 
- [ ] Any new/modified methods have been properly documented using Doxygen. 
- [x] Fast DDS test suite has been run locally. 
- [ ] Changes are ABI compatible. 
- [ ] Changes are API compatible. 
- [ ] Documentation builds and tests pass locally. 
- [ ] New feature has been added to the `versions.md` file (if applicable).
- [ ] New feature has been documented/Current behavior is correctly described in the documentation. 

## Reviewer Checklist
- [ ] Check contributor checklist is correct.
- [ ] Check CI results: changes do not issue any warning.
- [ ] Check CI results: failing tests are unrelated with the changes.

### CODE REVIEW

**Comment by MiguelBarro** [comment]
Your correction has encouraged us to refactor a little the `LivelinessManager` 😂

**Comment by MiguelBarro** [comment]
@richiprosima Please test this for me 🤯

**Comment by MiguelBarro** [comment]
@richiprosima Please test this

**Comment by MiguelBarro** [comment]
@richiprosima Please test this

**Review by jsantiago-eProsima — APPROVED** [review]
LGTM

**Comment by MiguelCompany** [comment]
@mergifyio backport 2.6.x

**Pull request merged**
