### PR TITLE
StatusCondition implementation [11824]

### PR DESCRIPTION
**Pull request by MiguelCompany**

### CODE REVIEW

**Review by IkerLuengo — CHANGES_REQUESTED** [review]
There's this unit test failing because `get_statuscondition` is not unsupported anymore:
projectroot.test.unittest.dds.core.entity.EntityTests.unsupported_entity_methods

**Comment by MiguelCompany** [comment]
> There's this unit test failing because `get_statuscondition` is not unsupported anymore:
> projectroot.test.unittest.dds.core.entity.EntityTests.unsupported_entity_methods

Fixed on bd9d7f6

**Comment by MiguelCompany** [comment]
@IkerLuengo Test fixed

**Review by IkerLuengo — APPROVED** [review]
👍🏼

**Pull request merged**
