### PR TITLE
Fix acknowledge in Datasharing

### PR DESCRIPTION
**Pull request by richiware**
## Description

Implementing Ownership it was detected this bug. A change removed by history (and not read yet by user) is not being
acked correctly.

This PR fixes this.

## Contributor Checklist
- [x] Commit messages follow the project guidelines. 
- [x] The code follows the style guidelines of this project. 
- [x] Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added. 
- [ ] Any new/modified methods have been properly documented using Doxygen. 
- [ ] Fast DDS test suite has been run locally. 
- [x] Changes are ABI compatible. 
- [x] Changes are API compatible. 
- [ ] Documentation builds and tests pass locally. 
- [ ] New feature has been added to the `versions.md` file (if applicable).
- [ ] New feature has been documented/Current behavior is correctly described in the documentation. 

## Reviewer Checklist
- [ ] Check contributor checklist is correct.
- [ ] Check CI results: changes do not issue any warning.
- [ ] Check CI results: failing tests are unrelated with the changes.

### CODE REVIEW

**Review by MiguelCompany — CHANGES_REQUESTED** [review]
Could we have a test for the corner case of `get_unread_count(true)` ?

**Comment by richiware** [comment]
@richiprosima please test this

**Comment by MiguelCompany** [comment]
@richiprosima Please test this

**Comment by MiguelCompany** [comment]
@mergifyio backport 2.6.x

**Pull request merged**
