### PR TITLE
WIP Revert #2785

### PR DESCRIPTION
**Pull request by Blast545**
## Description

It seems this commit introduced various build regressions on the nightly_win_deb jobs of the ROS2 buildfarm.
Reference: https://ci.ros2.org/view/nightly/job/nightly_win_deb/2425/
Issue: https://github.com/ros2/geometry2/issues/543

It was a flaky hang that appeared not so often, but now it has happened three times in a row. We are checking if this PR solves the hang situation.

## Contributor Checklist
- [x] Commit messages follow the project guidelines. 
- [x] The code follows the style guidelines of this project. 
- [ ] Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added. 
- [ ] Any new/modified methods have been properly documented using Doxygen. 
- [ ] Fast DDS test suite has been run locally. 
- [ ] Changes are ABI compatible. 
- [ ] Changes are API compatible. 
- [ ] Documentation builds and tests pass locally. 
- [ ] New feature has been added to the `versions.md` file (if applicable).
- [ ] New feature has been documented/Current behavior is correctly described in the documentation. 

## Reviewer Checklist
- [ ] Check contributor checklist is correct.
- [ ] Check CI results: changes do not issue any warning.
- [ ] Check CI results: failing tests are unrelated with the changes.

### CODE REVIEW

**Comment by MiguelCompany** [comment]
@Blast545 Could you check with #2868? It fixes an access on a deleted object when deleting a Topic.

**Comment by MiguelCompany** [comment]
@richiprosima please test this

**Comment by Blast545** [comment]
FYI: @Crola1702

**Comment by Blast545** [comment]
> @Blast545 Could you check with https://github.com/eProsima/Fast-DDS/pull/2868? It fixes an access on a deleted object when deleting a Topic.

Yes, I will! We were still verifying if we were able to reproduce the error with current main.

**Comment by Blast545** [comment]
We weren't able to replicate this problem when we started testing this PR, and the problem hasn't appeared again in our buildfarms.

Probably the problem was fixed after: https://github.com/eProsima/Fast-DDS/pull/2868, Thanks!

**Comment by MiguelCompany** [comment]
> Probably the problem was fixed after: #2868, Thanks!

Either that or #2851

**Pull request closed without merging**
