### PR TITLE
[20313] Allow single listening port on TCP

### PR DESCRIPTION
**Pull request by jepemi**
## Description

When several listening ports are added to the TCP transport, the data communication does not work or, if it does, it is in an undesired way. Servers create an acceptor on each of the listening ports. Since the server locators sent in the discovery phase only include the first added listening port, clients connected to another of the listening ports never find the resource that their initial peer initially created and end up creating a new channel for the locators obtained from the discovery data. If this new resource manages to connect, a new thread is created on both sides.

This PR limits the amount of listening ports to one, which effectively will only create an acceptor on the first indicated listening port. If more listening ports are passed, those are ignored. 

- This PR depends on #4297 and must be merged after that one.

## Contributor Checklist
- [x] Commit messages follow the project guidelines. 
- [x] The code follows the style guidelines of this project. 
- [x] Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
- [x] Any new/modified methods have been properly documented using Doxygen. 
- [x] Changes are ABI compatible. 
- [x] Changes are API compatible. 
- N/A New feature has been added to the `versions.md` file (if applicable).
- [x] New feature has been documented/Current behavior is correctly described in the documentation. 
 Related documentation PR: eProsima/Fast-DDS-docs#717
- [x] Applicable backports have been included in the description.

## Reviewer Checklist
- [x] The PR has a milestone assigned.
- [x] The title and description correctly express the PR's purpose.
- [x] Check contributor checklist is correct.
- [x] Check CI results: changes do not issue any warning.
- [x] Check CI results: failing tests are unrelated with the changes.

### CODE REVIEW

**Review by MiguelCompany — DISMISSED** [review]

**Comment by MiguelCompany** [comment]
Moved to 2.14, since this changes behavior

**Comment by MiguelCompany** [comment]
@jepemi This has some conflicts that need to be resolved before reviewing

**Review by MiguelCompany — APPROVED** [review]
LGTM with green CI

**Review by MiguelCompany — CHANGES_REQUESTED** [review]
Please fix warnings on Windows (signed / unsigned comparisons in the test)

**Review by MiguelCompany — DISMISSED** [review]
LGTM with green CI

**Review by MiguelCompany — APPROVED** [review]

**Comment by EduPonz** [comment]
@richiprosima please test this

**Comment by JesusPoderoso** [comment]
Although Jenkins Mac CI has not been run, Mac GitHub CI passes.
This PR is Ready to merge!

**Comment by MiguelCompany** [comment]
@jepemi This is ready to merge, but I think a documentation PR describing the limitation is necessary

**Pull request merged**
