### PR TITLE
Adding content filter interfaces [13290]

### PR DESCRIPTION
**Pull request by MiguelCompany**
This PR prepares all the necessary interfaces for the implementation of content filters in the reader side.

### CODE REVIEW

**Comment by JLBuenoLopez-eProsima** [comment]
This test is failing:

```
unittest.dds.participant.ParticipantTests.UnsupportedMethods
```

`DomainParticipant::delete_contentfilteredtopic` is implemented in this PR

**Comment by MiguelCompany** [comment]
@richiprosima Please test windows

**Review by EduPonz — CHANGES_REQUESTED** [review]
I'd appreciate if the negative case could cover all the possible cases

**Review by EduPonz — DISMISSED** [review]
LGTM

**Review by EduPonz — APPROVED** [review]

**Pull request merged**
