### PR TITLE
[13326] Update types using last Fast DDS Gen v2.1.0 release candidate

### PR DESCRIPTION
**Pull request by JLBuenoLopez-eProsima**
Use Fast DDS Gen generated files directly

Signed-off-by: JLBuenoLopez-eProsima <joseluisbueno@eprosima.com>

### CODE REVIEW

**Comment by MiguelCompany** [comment]
This does not build on Mac: http://jenkins.eprosima.com:8080/view/Fast%20DDS/job/fastdds_mac/1475/

**Comment by MiguelCompany** [comment]
* Mac: [Build Status](http://jenkins.eprosima.com:8080/view/Fast%20DDS/job/fastdds_mac/1476/)

**Comment by JLBuenoLopez-eProsima** [comment]
* Linux: [Build Status](http://ci.intranet.eprosima.com:8080/view/Fast%20DDS/job/fastdds_linux/1672/)

**Review by JLBuenoLopez-eProsima — COMMENTED** [review]
Changes LGTM but being the PR author I cannot approve them

**Review by jsantiago-eProsima — DISMISSED** [review]
Changes look good to me too. Approved.

**Review by jsantiago-eProsima — APPROVED** [review]
LGTM

**Pull request merged**
