### PR TITLE
[19967] Define a super client by environment variable 

### PR DESCRIPTION
**Pull request by elianalf**
## Description

Define a super client setting a new environment variable ROS_SUPER_CLIENT

@Mergifyio backport 2.12.x 2.11.x 2.10.x 2.6.x

## Contributor Checklist
- [x] Commit messages follow the project guidelines. 
- [x] The code follows the style guidelines of this project. 
- [x] Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally; test case: eProsima/Discovery-Server#65 
- [x] Any new/modified methods have been properly documented using Doxygen. 
- [x] Changes are ABI compatible. 
- [x] Changes are API compatible. 
- **N/A** New feature has been added to the `versions.md` file (if applicable).
- [x] New feature has been documented/Current behavior is correctly described in the documentation. 
    Related documentation PR: eProsima/Fast-DDS-docs#596
- [x] Applicable backports have been included in the description.

## Reviewer Checklist
- [x] The PR has a milestone assigned.
- [x] Check contributor checklist is correct.
- [x] Check CI results: changes do not issue any warning.
- [x] Check CI results: failing tests are unrelated with the changes.

### CODE REVIEW

**Comment by EduPonz** [comment]
@richiprosima please test mac

**Review by MiguelCompany — CHANGES_REQUESTED** [review]
Please remove commit b0651d09484806986b63b72f231641ddd21373dc from the history

**Comment by elianalf** [comment]
@richiprosima please test this

**Review by MiguelCompany — APPROVED** [review]
🏅

**Comment by MiguelCompany** [comment]
@richiprosima Please test this

**Comment by MiguelCompany** [comment]
Testing with discovery server changes:

[Build Status](http://jenkins.eprosima.com:8080/job/discovery_server_linux/4591/)

**Comment by EduPonz** [comment]
@richiprosima please test windows

**Pull request merged**
