### PR TITLE
[18071] Update classes to implement interfaces

### PR DESCRIPTION
**Pull request by JesusPoderoso**
## Contributor Checklist
- [x] Commit messages follow the project guidelines. 
- [x] The code follows the style guidelines of this project. 
- **N/A** Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
- [x] Any new/modified methods have been properly documented using Doxygen. 
- [x] Changes are ABI compatible. 
- [x] Changes are API compatible. 
- **N/A** New feature has been added to the `versions.md` file (if applicable).
- **N/A** New feature has been documented/Current behavior is correctly described in the documentation. 
    
- **N/A** Applicable backports have been included in the description.

## Reviewer Checklist
- [x] The PR has a milestone assigned.
- [x] Check contributor checklist is correct.
- [x] Check CI results: changes do not issue any warning.
- [x] Check CI results: failing tests are unrelated with the changes.

### CODE REVIEW

**Review by JesusPoderoso — COMMENTED** [review]
Last updates performed by @Mario-DL (from [cb48f56](https://github.com/eProsima/Fast-DDS/pull/3754/commits/cb48f561091a061d1cf1e54ba9a4f6c757df13f0) to [6ea013b](https://github.com/eProsima/Fast-DDS/pull/3754/commits/6ea013bfb41b8844d92f6cd7d11981a6fc7b14f3)) LGTM

**Comment by Mario-DL** [comment]
@richiprosima please test this

**Comment by Mario-DL** [comment]
@richiprosima please test this

**Review by JesusPoderoso — COMMENTED** [review]
LGTM

**Review by Mario-DL — APPROVED** [review]

**Comment by Mario-DL** [comment]
@richiprosima please test windows

**Pull request merged**
