### PR TITLE
Persistence guid hotfixes [12680]

### PR DESCRIPTION
**Pull request by jparisu**
Signed-off-by: jparisu <javierparis@eprosima.com>

### CODE REVIEW

**Comment by jparisu** [comment]
@richiprosima please test this

**Comment by MiguelCompany** [comment]
@richiprosima Please test windows

**Comment by MiguelCompany** [comment]
@richiprosima Please test windows

**Comment by MiguelCompany** [comment]
@mergifyio backport 2.3.x

**Comment by EduPonz** [comment]
@Mergifyio backport 2.1.x

**Pull request merged**
