### PR TITLE
Fix compilation when building static library [21059]

### PR DESCRIPTION
**Pull request by richiware**
## Description

Static library generation is not working in 3.x. This PR fixes it.

## Contributor Checklist

- [x] Commit messages follow the project guidelines. 
- [x] The code follows the style guidelines of this project. 
- *N/A* Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
- *N/A* Any new/modified methods have been properly documented using Doxygen. 
- *N/A* Any new configuration API has an equivalent XML API (with the corresponding XSD extension) 
- *N/A* Changes are backport compatible: they do **NOT** break ABI nor change library core behavior. 
- *N/A* Changes are API compatible. 
- *N/A* New feature has been added to the `versions.md` file (if applicable).
- *N/A* New feature has been documented/Current behavior is correctly described in the documentation. 
    
- *N/A* Applicable backports have been included in the description.

## Reviewer Checklist

- [x] The PR has a milestone assigned.
- [x] The title and description correctly express the PR's purpose.
- [x] Check contributor checklist is correct.
- [x] Check CI results: changes do not issue any warning.
- [x] Check CI results: failing tests are unrelated with the changes.

### CODE REVIEW

**Comment by MiguelCompany** [comment]
Manual build with `-DBUILD_SHARED_LIBS=OFF`:
- [Ubuntu](https://github.com/eProsima/Fast-DDS/actions/runs/9159284546/job/25179344175)

**Comment by MiguelCompany** [comment]
@mergifyio rebase

**Comment by MiguelCompany** [comment]
@richiware Build failed when linking in [this manual run](https://github.com/eProsima/Fast-DDS/actions/runs/9253694141) where I passed `-DBUILD_SHARED_LIBS=OFF`

**Comment by MiguelCompany** [comment]
@richiprosima Please test_3 discovery-server

**Review by MiguelCompany — APPROVED** [review]
LGTM with green build.

Local build with -DBUILD_SHARED_LIBS=OFF success on windows and Ubuntu

**Comment by MiguelCompany** [comment]
@mergifyio rebase

**Comment by MiguelCompany** [comment]
@richiprosima Please test_3 discovery-server

**Comment by elianalf** [comment]
@richiprosima Please test_3 discovery-server

**Pull request merged**
