### PR TITLE
Fix tests with Log: wait for Log background thread initialization on the first queued entry [16948]

### PR DESCRIPTION
**Pull request by irenebm**
Signed-off-by: Irene Bandera <irenebandera@eprosima.com>

## Description
https://github.com/eProsima/Fast-DDS/tree/bug/logError

@Mergifyio backport 2.10.x 2.9.x 2.6.x

## Contributor Checklist
- [ ] Commit messages follow the project guidelines. 
- [x] The code follows the style guidelines of this project. 
- **N/A** Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
- **N/A** Any new/modified methods have been properly documented using Doxygen. 
- [x] Changes are ABI compatible. 
- [x] Changes are API compatible. 
- **N/A** Documentation builds and tests pass locally. 
- **N/A** New feature has been added to the `versions.md` file (if applicable).
- **N/A** New feature has been documented/Current behavior is correctly described in the documentation. 

- [x] Applicable backports have been included in the description.

## Reviewer Checklist
- [x] Check contributor checklist is correct.
- [x] Check CI results: changes do not issue any warning.
- **N/A** Check CI results: failing tests are unrelated with the changes.

### CODE REVIEW

**Review by MiguelBarro — APPROVED** [review]
LGTM

**Comment by jparisu** [comment]
@richiprosima please test this

**Review by JesusPoderoso — CHANGES_REQUESTED** [review]
Please, complete the contributor checklist

**Review by JesusPoderoso — APPROVED** [review]

**Comment by JesusPoderoso** [comment]
@Mergifyio backport 2.10.x 2.9.x 2.6.x

**Comment by JesusPoderoso** [comment]
@richiprosima please test this

**Comment by JesusPoderoso** [comment]
@richiprosima please test windows

**Pull request merged**
