### PR TITLE
oss-fuzz integration

### PR DESCRIPTION
**Pull request by catenacyber**
cc @MiguelCompany 

Oss-fuzz build is failing because the signature of `processCDRMsg` changed recently
cf https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=34310

This should fix it

### CODE REVIEW

**Review by MiguelCompany — CHANGES_REQUESTED** [review]
Changes look good to me, but please fix [DCO](https://github.com/eProsima/Fast-DDS/pull/1968/checks?check_run_id=2600298137) and [linters](http://jenkins.eprosima.com:8080/job/fastdds_github_uncrustify/2467/)

**Comment by catenacyber** [comment]
Is that ok so ?

**Review by MiguelCompany — APPROVED** [review]
LGTM  now. Thanks for your contribution!

**Comment by phretor** [comment]
@MiguelCompany here #2273 + https://github.com/google/oss-fuzz/compare/master...phretor:fast-dds/refactor?expand=1

**Pull request merged**
