### PR TITLE
Fix dns filter in CMakeLists file

### PR DESCRIPTION
**Pull request by elianalf**
## Description

Fix dns filter of tests in CMakeLists file 

## Contributor Checklist
- N/A Commit messages follow the project guidelines. 
- [X] The code follows the style guidelines of this project. 
- N/A Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
- N/A Any new/modified methods have been properly documented using Doxygen. 
- N/A Changes are ABI compatible. 
- N/A Changes are API compatible. 
- N/A New feature has been added to the `versions.md` file (if applicable).
- N/A New feature has been documented/Current behavior is correctly described in the documentation. 
    
- [X] Applicable backports have been included in the description.

@Mergifyio backport 2.12.x 2.11.x 2.10.x 

## Reviewer Checklist
- [x] The PR has a milestone assigned.
- [x] Check contributor checklist is correct.
- [x] Check CI results: changes do not issue any warning.
- [x] Check CI results: failing tests are unrelated with the changes.

### CODE REVIEW

**Comment by elianalf** [comment]
@Mergifyio backport 2.12.x 2.11.x 2.10.x

**Review by JesusPoderoso — APPROVED** [review]
LGTM with green CI

**Comment by JesusPoderoso** [comment]
@richiprosima please test this

**Comment by EduPonz** [comment]
@richiprosima please test mac

**Comment by EduPonz** [comment]
@Mergifyio backport 2.12.x 2.11.x 2.10.x

**Pull request merged**
