### PR TITLE
Fix asymmetric whitelist matching [19035]

### PR DESCRIPTION
**Pull request by juanlofer-eprosima**
## Description

Matching two local participants through UDP/TCP transport currently fails when only one of them sets an interface whitelist. In particular, the problematic cases are only including the loopback interface (**A**), or including all except the loopback interface (**B**).

The reason for this is that Fast DDS internally performs an optimization consisting in transforming a local locator to localhost (``NetworkFactory::transform_remote_locators``) whenever possible. This way, communication is performed through the loopback interface, which is allegedly more robust to changes in the environment.
However, the only input for determining whether this transformation should be performed is each transport's **own** interface whitelist. This implies that in some cases the transformation will be wrongly performed as the remote transport may not be listening on localhost (**B**).
Another issue with this transformation method is that it boths attempts conversion to localhost as well as filters locators based on one's interface whitelist. This explains why **A** arises, as the received remote (local) locator gets filtered out for being different than localhost.

This PR attempts to fix the issue by sending in discovery a new network configuration parameter, which for the moment only includes whether a participant is listening on localhost (depending on its whitelist). Four (plus 28 unused) different bits encoding this information are sent, each for a different transport kind (UDPv4, UDPv6, TCPv4 and TCPv6). 
An extended ``NetworkFactory::transform_remote_locators`` is added leveraging this information, so conversion to localhost is only performed when both remote and local participants allow for it.

**Behaviour changes:**
- Transformation to localhost is no longer attempted in Initial Peers and Discovery Server. This is because the remote's participant network configuration is only shared through discovery, and hence in these two cases it is not available.

@Mergifyio backport 2.11.x 2.10.x 2.6.x

## Contributor Checklist
- [x] Commit messages follow the project guidelines. 
- [x] The code follows the style guidelines of this project. 
- [x] Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
- [x] Any new/modified methods have been properly documented using Doxygen. 
- [x] Changes are ABI compatible. 
- [x] Changes are API compatible. 
- **N/A** New feature has been added to the `versions.md` file (if applicable).
- **N/A** New feature has been documented/Current behavior is correctly described in the documentation. 
    
- [x] Applicable backports have been included in the description.

## Reviewer Checklist
- [x] The PR has a milestone assigned.
- [x] Check contributor checklist is correct.
- [ ] Check CI results: changes do not issue any warning.
- [ ] Check CI results: failing tests are unrelated with the changes.

### CODE REVIEW

**Comment by juanlofer-eprosima** [comment]
Compatibility report: [compat_report.zip](https://github.com/eProsima/Fast-DDS/files/12103243/compat_report.zip)

**Comment by EduPonz** [comment]
@richiprosima please test this

**Comment by EduPonz** [comment]
@Mergifyio backport 2.11.x 2.10.x 2.6.x

**Review by EduPonz — DISMISSED** [review]

**Comment by EduPonz** [comment]
@richiprosima please test mac

**Comment by EduPonz** [comment]
@richiprosima please test mac

**Comment by EduPonz** [comment]
@richiprosima please test mac

**Comment by rsanchez15** [comment]
@Mergifyio backport eprosima/integration

**Comment by MiguelCompany** [comment]
@richiprosima Please test mac

**Comment by JesusPoderoso** [comment]
@richiprosima please test mac

**Comment by juanlofer-eprosima** [comment]
@richiprosima please test this

**Comment by juanlofer-eprosima** [comment]
@richiprosima please test this

**Comment by juanlofer-eprosima** [comment]
@richiprosima please test this

**Review by EduPonz — APPROVED** [review]

**Pull request merged**
