### PR TITLE
[20121] Remove unnecessary TCP warning

### PR DESCRIPTION
**Pull request by jepemi**
## Description

When sending TCP messages, the locator selector from the publisher includes the locators to which messages will be sent. These locators are compared with the send_resource_list_. If there are more than two endpoints available (locators A and B), the following checks are made: A==A, A==B, B==A, B==B.

Successful checks end in trying to send data to the correspondent locator.
Mismatching checks produce a warning, though it is actually correct behavior.

@Mergifyio backport 2.12.x 2.11.x 2.10.x 2.6.x

## Contributor Checklist
- [x] Commit messages follow the project guidelines. 
- [x] The code follows the style guidelines of this project. 
- N/A Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
- N/A Any new/modified methods have been properly documented using Doxygen. 
- [x] Changes are ABI compatible. 
- [x] Changes are API compatible. 
- N/A New feature has been added to the `versions.md` file (if applicable).
- N/A New feature has been documented/Current behavior is correctly described in the documentation. 
    
- [x] Applicable backports have been included in the description.

## Reviewer Checklist
- [x] The PR has a milestone assigned.
- [x] The title and description correctly express the PR's purpose.
- [x] Check contributor checklist is correct.
- [ ] Check CI results: changes do not issue any warning.
- [ ] Check CI results: failing tests are unrelated with the changes.

### CODE REVIEW

**Comment by jepemi** [comment]
@Mergifyio backport 2.12.x 2.11.x 2.10.x 2.6.x

**Comment by jepemi** [comment]
@richiprosima please test this

**Review by MiguelCompany — APPROVED** [review]

**Comment by jepemi** [comment]
@richiprosima please test mac test discovery_server_linux

**Comment by jepemi** [comment]
@richiprosima please test this

**Pull request merged**
