### PR TITLE
Branch out 3.0.x

### PR DESCRIPTION
**Pull request by MiguelCompany**
## Description

Branching out 3.0.x branch after turning master into 3.1.x on #5285

## Contributor Checklist

- [x] Commit messages follow the project guidelines. 
- _N/A_: The code follows the style guidelines of this project. 
- _N/A_: Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
- _N/A_: Any new/modified methods have been properly documented using Doxygen. 
- _N/A_: Any new configuration API has an equivalent XML API (with the corresponding XSD extension) 
- _N/A_: Changes are backport compatible: they do **NOT** break ABI nor change library core behavior. 
- _N/A_: Changes are API compatible. 
- _N/A_: New feature has been added to the `versions.md` file (if applicable).
- _N/A_: New feature has been documented/Current behavior is correctly described in the documentation. 
    
- _N/A_: Applicable backports have been included in the description.

## Reviewer Checklist

- [x] The PR has a milestone assigned.
- [x] The title and description correctly express the PR's purpose.
- [x] Check contributor checklist is correct.
- [x] If this is a critical bug fix, backports to the critical-only supported branches have been requested.
- [x] Check CI results: changes do not issue any warning.
- [x] Check CI results: failing tests are unrelated with the changes.

### CODE REVIEW

**Review by Mario-DL — COMMENTED** [review]
Should we also change the `fallback_branch` in the `reusable-*` workflows ?

**Comment by MiguelCompany** [comment]
> Should we also change the `fallback_branch` in the `reusable-*` workflows ?

It seems this is only necessary on `reusable-ubuntu-ci.yml`

**Comment by MiguelCompany** [comment]
> > Should we also change the `fallback_branch` in the `reusable-*` workflows ?
> 
> It seems this is only necessary on `reusable-ubuntu-ci.yml`

Done in a838371175e5579ff8a0250e8885e1538aa8665e

**Review by Mario-DL — APPROVED** [review]
LGTM

**Review by Mario-DL — APPROVED** [review]
LGTM

**Pull request merged**
