### PR TITLE
Avoid foonathan debug usage [8604]

### LINKED ISSUE #1245: Cross compiling FastRTPS [8587]
Fonnathan memory is able to cross compile now - [Check this issue](https://github.com/foonathan/memory/issues/72)

But when cross compiling FastRTPS it fails with the following errors:
```
| /build-fastrtps/tmp/work/i586-poky-linux/fastrtps/1.0-r0/git/src/cpp/rtps/reader/WriterProxy.cpp:56:46: error: 'set_node_size' is not a member of 'memory'
|  constexpr size_t changes_node_size = memory::set_node_size<std::pair<size_t, SequenceNumber_t> >::value;
|                                               ^~~~~~~~~~~~~
| /build-fastrtps/tmp/work/i586-poky-linux/fastrtps/1.0-r0/git/src/cpp/rtps/reader/WriterProxy.cpp:56:46: note: suggested alternative: 'bad_node_size'
|  constexpr size_t changes_node_size = memory::set_node_size<std::pair<size_t, SequenceNumber_t> >::value;
|                                               ^~~~~~~~~~~~~
|                                               bad_node_size
| /build-fastrtps/tmp/work/i586-poky-linux/fastrtps/1.0-r0/git/src/cpp/rtps/reader/WriterProxy.cpp:56:96: error: expected primary-expression before '>' token
|  constexpr size_t changes_node_size = memory::set_node_size<std::pair<size_t, SequenceNumber_t> >::value;
|                                                                                                 ^
| /build-fastrtps/tmp/work/i586-poky-linux/fastrtps/1.0-r0/git/src/cpp/rtps/reader/WriterProxy.cpp:56:99: error: '::value' has not been declared
|  constexpr size_t changes_node_size = memory::set_node_size<std::pair<size_t, SequenceNumber_t> >::value;
|                                                                                                    ^~~~~
| src/cpp/CMakeFiles/fastrtps.dir/build.make:665: recipe for target 'src/cpp/CMakeFiles/fastrtps.dir/rtps/reader/WriterProxy.cpp.o' failed
| make[2]: *** [src/cpp/CMakeFiles/fastrtps.dir/rtps/reader/WriterProxy.cpp.o] Error 1
| make[2]: *** Waiting for unfinished jobs....
| In file included from /build-fastrtps/tmp/work/i586-poky-linux/fastrtps/1.0-r0/git/src/cpp/rtps/reader/RTPSReader.cpp:23:0:
| /build-fastrtps/tmp/work/i586-poky-linux/fastrtps/1.0-r0/git/src/cpp/rtps/reader/ReaderHistoryState.hpp:37:24: error: 'map_node_size' is not a member of 'foonathan::memory'
|      foonathan::memory::map_node_size<std::pair<size_t, std::pair<GUID_t, GUID_t>>>::value;
|                         ^~~~~~~~~~~~~
| /build-fastrtps/tmp/work/i586-poky-linux/fastrtps/1.0-r0/git/src/cpp/rtps/reader/ReaderHistoryState.hpp:37:24: note: suggested alternative: 'bad_node_size'
|      foonathan::memory::map_node_size<std::pair<size_t, std::pair<GUID_t, GUID_t>>>::value;
|                         ^~~~~~~~~~~~~
|                         bad_node_size
```

These functions should be defined in `/usr/include/foonathan_memory/foonathan/memory/detail/container_node_sizes_impl.hpp` but in case of cross compiling, this file only include the following line:
```
#define FOONATHAN_MEMORY_NO_NODE_SIZE
```

According to _razr_ from foonathan memory, these errors could be handled from FastRTPS.

## Steps to Reproduce
1. Cross compile latest foonthan memory  "7b39ea6"
2. Cross compile FastRTPS

### PR DESCRIPTION
**Pull request by MiguelCompany**
This PR should fix #1245 by avoiding calls to `foonathan::memory::xxx_node_size` when `FOONATHAN_MEMORY_NO_NODE_SIZE` is defined.

In that case, more memory than the strictly necessary may be used, as we will use the maximum possible overhead for each node.

### CODE REVIEW

**Comment by MiguelCompany** [comment]
@MiguelBarro 
> * Making foonathan introspection the default forces us to check if the nathan auxiliary tool (nodesize_dbg) gives the right values in the usual platforms (set<SequenceNumber_t> issue)

That is why, on the impl/foonathan files for set and map, I am using the `std::pair<size_t, value_type>` trick.

**Comment by MiguelBarro** [comment]
> @MiguelBarro
> 
> > * Making foonathan introspection the default forces us to check if the nathan auxiliary tool (nodesize_dbg) gives the right values in the usual platforms (set<SequenceNumber_t> issue)
> 
> That is why, on the impl/foonathan files for set and map, I am using the `std::pair<size_t, value_type>` trick.

Very witty, I didn't notice that. We should comment that on the code to prevent user misunderstandings (or us forgetting why the size_t is there 😄).

**Comment by richiware** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/2155/)
* Mac [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/1945/)
* Windows [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/2150/)

**Comment by MiguelCompany** [comment]
@MiguelBarro I added documentation and checks for the configuration on implementation selection as well as documentation on the `std::pair<size_t, value_type>` workaround.

**Comment by richiware** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/2160/)
* Mac [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/1950/)
* Windows [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/2155/)

**Pull request merged**
