### PR TITLE
[19907] Enable configuration of thread setting for all threads

### PR DESCRIPTION
**Pull request by EduPonz**
## Description

This PR adds the possibility to configure various thread settings for all Fast DDS threads, both through the C++ API, and also using XML configuration files.
Those settings are:
* Scheduling policy
* Priority
* Affinity
* Stack size

## Contributor Checklist
- [x] Commit messages follow the project guidelines. 
- [x] The code follows the style guidelines of this project. 
- [x] Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
- [x] Any new/modified methods have been properly documented using Doxygen. 
- *N/A* Changes are ABI compatible: **Not applicable as this PR targets a minor version** 
- [x] Changes are API compatible. 
- [x] New feature has been added to the `versions.md` file (if applicable).
- [x] New feature has been documented/Current behavior is correctly described in the documentation. eProsima/Fast-DDS-docs#590
- *N/A* Applicable backports have been included in the description: **Not applicable as this PR targets a minor version**

## Reviewer Checklist
- [x] The PR has a milestone assigned.
- [x] Check contributor checklist is correct.
- [x] Check CI results: changes do not issue any warning.
- [x] Check CI results: failing tests are unrelated with the changes.

### CODE REVIEW

**Comment by EduPonz** [comment]
@richiprosima please test mac

**Comment by EduPonz** [comment]
@richiprosima please test mac

**Comment by EduPonz** [comment]
@richiprosima please test this

**Comment by EduPonz** [comment]
@richiprosima please test mac

**Comment by EduPonz** [comment]
@richiprosima please test this

**Review by MiguelCompany — APPROVED** [review]

**Pull request merged**
