### PR TITLE
[17291] Add tests to check that remote builtin endpoints are honored

### PR DESCRIPTION
**Pull request by jsantiago-eProsima**
This test makes sure that the remote builtin endpoint configuration is honored, reducing the number of HEARTBEAT/ACKNACK messages being sent depending on the configuration.

## Description

@Mergifyio backport 2.9.x

## Contributor Checklist
- [x] Commit messages follow the project guidelines. 
- [x] The code follows the style guidelines of this project. 
- [x] Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
- [N/A] Any new/modified methods have been properly documented using Doxygen. 
- [x] Changes are ABI compatible. 
- [x] Changes are API compatible. 
- [N/A] New feature has been added to the `versions.md` file (if applicable).
- [N/A] New feature has been documented/Current behavior is correctly described in the documentation. 
    
- [x] Applicable backports have been included in the description.

## Reviewer Checklist
- [x] The PR has a milestone assigned.
- [x] Check contributor checklist is correct.
- [ ] Check CI results: changes do not issue any warning.
- [ ] Check CI results: failing tests are unrelated with the changes.

### CODE REVIEW

**Comment by JLBuenoLopez-eProsima** [comment]
@richiprosima please test this

**Review by JLBuenoLopez-eProsima — CHANGES_REQUESTED** [review]
Uncrustify is also complaining

**Comment by jsantiago-eProsima** [comment]
@richiprosima please test windows

**Comment by MiguelCompany** [comment]
@Mergifyio backport 2.9.x

**Comment by MiguelCompany** [comment]
@mergifyio backport 2.6.x

**Pull request merged**
