### PR TITLE
Avoid using private header on public ones

### PR DESCRIPTION
**Pull request by MiguelCompany**
Signed-off-by: Miguel Company <MiguelCompany@eprosima.com>

### CODE REVIEW

**Comment by richiware** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/3127/)
* Linux aarch64[Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux%20aarch64/345/)
* Mac [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/2791/)
* Windows [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/3159/)

**Review by EduPonz — APPROVED** [review]
LGTM

**Comment by EduPonz** [comment]
Windows failures are unrelated

**Comment by EduPonz** [comment]
Please include this in 2.1.x

**Pull request merged**
