### PR TITLE
[20994] Consider library behavior changes as ABI breaks in the PR template checklist

### PR DESCRIPTION
**Pull request by JesusPoderoso**
## Description
This PR updates the pull request template to take into consideration possible library core behavior changes, and consider them as in the same level as ABI breaks.

@Mergifyio backport 2.14.x 2.13.x 2.10.x 2.6.x

## Contributor Checklist

- [x] Commit messages follow the project guidelines. 
- __N/A__ The code follows the style guidelines of this project. 
- __N/A__ Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
- __N/A__ Any new/modified methods have been properly documented using Doxygen. 
- __N/A__ Any new configuration API has an equivalent XML API (with the corresponding XSD extension) 
- __N/A__ Changes are backport compatible: they do **NOT** break ABI nor change library core behavior. 
- __N/A__ Changes are API compatible. 
- __N/A__ New feature has been added to the `versions.md` file (if applicable).
- __N/A__ New feature has been documented/Current behavior is correctly described in the documentation. 
    
- [x] Applicable backports have been included in the description.

## Reviewer Checklist

- [x] The PR has a milestone assigned.
- [x] The title and description correctly express the PR's purpose.
- [x] Check contributor checklist is correct.
- [x] Check CI results: changes do not issue any warning.
- [x] Check CI results: failing tests are unrelated with the changes.

### CODE REVIEW

**Comment by JesusPoderoso** [comment]
@richiprosima please test this

**Review by EduPonz — APPROVED** [review]

**Comment by EduPonz** [comment]
@JesusPoderoso please rebase on 3.0.x-devel and update the backport list

**Review by EduPonz — APPROVED** [review]

**Comment by JesusPoderoso** [comment]
@richiprosima please test this

**Review by EduPonz — APPROVED** [review]

**Comment by EduPonz** [comment]
@Mergifyio backport 2.14.x 2.13.x 2.10.x 2.6.x

**Pull request merged**
