### PR TITLE
Add an explicit build dependency on libssl-dev

### PR DESCRIPTION
**Pull request by cottsay**
It appears that libasio-dev is pulling in this dependency at build time, but it is actually directly needed to build Fast-DDS with SECURITY=ON.

### CODE REVIEW

**Review by MiguelCompany — CHANGES_REQUESTED** [review]
We already have it as `build_export_depend` and `exec_depend`. Should we just convert it to a `depend` ?

**Comment by cottsay** [comment]
> We already have it as `build_export_depend` and `exec_depend`. Should we just convert it to a `depend` ?

Works for me, done in b3e9837.

**Review by MiguelCompany — CHANGES_REQUESTED** [review]
Please fix DCO

**Review by MiguelCompany — APPROVED** [review]

**Comment by MiguelCompany** [comment]
@cottsay Thanks for your contribution!

**Pull request merged**
