### PR TITLE
Fix compile error on mac [9737]

### PR DESCRIPTION
**Pull request by imontesino**
Signed-off-by: Ignacio Montesino <ignaciomontesino@eprosima.com>

### CODE REVIEW

**Review by MiguelCompany — APPROVED** [review]
LGTM

**Comment by richiware** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/2988/)
* Linux aarch64Build Status
* Mac Build Status
* Windows [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/2999/)

**Comment by richiware** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/2998/)
* Linux aarch64Build Status
* Mac [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/2688/)
* Windows [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/3009/)

**Comment by MiguelCompany** [comment]
I will merge this, since it solves the build error. We will address the warnings on a separate PR.

**Pull request merged**
