### PR TITLE
[20679] Run Github Ubuntu CI on PRs

### PR DESCRIPTION
**Pull request by EduPonz**
## Description

This PR:

1. Enables running Github Ubuntu CI on `pull_request` events.
2. Fixes hidden overloads erroneously left out by #4516 
3. Enables running Github CI on PRs targeting intermediate branches (not `master`). 

@Mergifyio backport 2.13.x 2.10.x 2.6.x

## Contributor Checklist

- [x] Commit messages follow the project guidelines. 
- [x] The code follows the style guidelines of this project. 
- _N/A_: Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
- _N/A_: Any new/modified methods have been properly documented using Doxygen. 
- [x] Changes are ABI compatible. 
- [x] Changes are API compatible. 
- _N/A_: New feature has been added to the `versions.md` file (if applicable).
- _N/A_: New feature has been documented/Current behavior is correctly described in the documentation. 
    
- [x] Applicable backports have been included in the description.

## Reviewer Checklist

- [x] The PR has a milestone assigned.
- [x] The title and description correctly express the PR's purpose.
- [x] Check contributor checklist is correct.
- [x] Check CI results: changes do not issue any warning.
- [x] Check CI results: failing tests are unrelated with the changes.

### CODE REVIEW

**Comment by EduPonz** [comment]
@richiprosima please test this

**Comment by EduPonz** [comment]
@richiprosima please test mac

**Comment by JesusPoderoso** [comment]
@richiprosima please test this

**Review by JesusPoderoso — DISMISSED** [review]
LGTM with green CI

**Review by JesusPoderoso — APPROVED** [review]
LGTM with green CI

**Comment by EduPonz** [comment]
CI passed on 5b29744

**Comment by EduPonz** [comment]
@Mergifyio backport 2.13.x 2.10.x 2.6.x

**Pull request merged**
