### PR TITLE
[18503] Use eProsima-CI external actions for mirror workflow [WIP]

### PR DESCRIPTION
**Pull request by JLBuenoLopez-eProsima**
## Description

This PR depends on eProsima/eProsima-CI#25. Once this PR is merged and released, the branch of the create PR action must be updated previous to merging.

## Contributor Checklist
- [x] Commit messages follow the project guidelines. 
- [N/A] The code follows the style guidelines of this project. 
- [N/A] Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
- [N/A] Any new/modified methods have been properly documented using Doxygen. 
- [N/A] Changes are ABI compatible. 
- [N/A] Changes are API compatible. 
- [N/A] New feature has been added to the `versions.md` file (if applicable).
- [N/A] New feature has been documented/Current behavior is correctly described in the documentation. 
    
- [N/A] Applicable backports have been included in the description.

## Reviewer Checklist
- [x] The PR has a milestone assigned.
- [x] Check contributor checklist is correct.
- [x] Check CI results: changes do not issue any warning.
- [x] Check CI results: failing tests are unrelated with the changes.

### CODE REVIEW

**Comment by JLBuenoLopez-eProsima** [comment]
@richiprosima please test this

**Comment by JesusPoderoso** [comment]
@richiprosima please test this

**Comment by JLBuenoLopez-eProsima** [comment]
@JesusPoderoso this PR requires a release in eProsima-CI repository. The version is pointing to, `v0.4`, does not exist yet. Also, it has the `skip-ci` label because the CI is not affected by the changes in the PR.

**Comment by JLBuenoLopez-eProsima** [comment]
I have rebased this PR and updated the version of the action to `v0` to use always the latest minor (so the mirror action can be upgraded if a new version of the external action is released).

**Review by JesusPoderoso — APPROVED** [review]
LGTM

**Pull request merged**
