### PR TITLE
DataReaderHistory [12400]

### PR DESCRIPTION
**Pull request by MiguelCompany**
This PR makes the DataReader use a new `DataReaderHistory` class with a correct implementation of instance_state and view_state.

### CODE REVIEW

**Comment by JLBuenoLopez-eProsima** [comment]
`versions.md` should be updated. To avoid future conflicts, please first rebase the branch.

**Review by JLBuenoLopez-eProsima — APPROVED** [review]
LGTM with greenish CI

**Review by JLBuenoLopez-eProsima — APPROVED** [review]
:+1:

**Comment by MiguelCompany** [comment]
@richiprosima Please test windows

**Comment by MiguelCompany** [comment]
@richiprosima Please test this

**Comment by MiguelCompany** [comment]
I have reproduced all windows and linux test failures locally on master with `--repeat-until-fail 100`

**Pull request merged**
