### PR TITLE
Include the right header when building for iOS

### PR DESCRIPTION
**Pull request by light-tech**
Signed-off-by: Lightech <lightech@outlook.com>

## Contributor Checklist
- [ ] Commit messages follow the project guidelines. 
- [ ] The code follows the style guidelines of this project. 
- [ ] Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added. 
- [ ] Any new/modified methods have been properly documented using Doxygen. 
- [ ] Fast DDS test suite has been run locally. 
- [ ] Changes are ABI compatible. 
- [ ] Changes are API compatible. 
- [ ] Documentation builds and tests pass locally. 
- [ ] New feature has been added to the `versions.md` file (if applicable).
- [ ] New feature has been documented/Current behavior is correctly described in the documentation. 

## Reviewer Checklist
- [ ] Check contributor checklist is correct.
- [ ] Check CI results: changes do not issue any warning.
- [ ] Check CI results: failing tests are unrelated with the changes.

### CODE REVIEW

**Review by MiguelBarro — APPROVED** [review]
LGTM with green CI

**Comment by light-tech** [comment]
Please refer to https://github.com/light-tech/ROS2-On-iOS for ROS2 building scripts for the iOS platform.

**Comment by MiguelCompany** [comment]
@richiprosima Please test this

**Comment by jsantiago-eProsima** [comment]
@richiprosima please test this

**Review by jsantiago-eProsima — APPROVED** [review]
Thanks for your contribution,

Mac CI (and all the other platforms' for that matter) seems unaffected by the changes, so I'll go ahead and approve this.

**Comment by MiguelCompany** [comment]
@mergifyio backport 2.9.x 2.8.x 2.6.x 2.1.x

**Pull request merged**
