### PR TITLE
Fix asan and undefined behavior error [10916]

### PR DESCRIPTION
**Pull request by princeward**
Fix two error reported by AddressSanitizer and UndefinedBehaviorSanitizer.

The AddressSanitizer error is trivial.

For the UndefinedBehaviorSanitizer error, left shifting a uint64 by 64 bits is considered undefined behavior. See this article for reference.

This is take 2 of an earlier PR: https://github.com/eProsima/Fast-DDS/pull/1834

### CODE REVIEW

**Comment by princeward** [comment]
Hi @MiguelCompany , thanks for reviewing in an previous version of this PR: https://github.com/eProsima/Fast-DDS/pull/1834. I opened this new PR since I messed up with DCO signoff in the previous one.

I've tested that the new change will pass both Address and UndefinedBehavior sanitizer now :D

Please let me what else is needed to merge this PR. Thank you!

**Review by MiguelCompany — DISMISSED** [review]
LGTM

**Comment by princeward** [comment]
Hi @MiguelCompany , thanks for approving. I see that some CI tests are failing. Are these legitimate concerns and actually caused by my PR?

**Comment by MiguelCompany** [comment]
@richiprosima Please test this

**Comment by IkerLuengo** [comment]
The piece of code making the bit shifting was used in several places, but only some of them were modified on this PR, breaking the logic and making the tests fail. Commit cf8c162 centralizes this code in a single place and solved the testing errors.

**Review by MiguelCompany — CHANGES_REQUESTED** [review]
LGTM with green CI.

**Comment by MiguelCompany** [comment]
Thank you @princeward and @IkerLuengo

**Pull request merged**
