### PR TITLE
[14052] Writer side content filter

### PR DESCRIPTION
**Pull request by MiguelCompany**
## Description

This PR adds support for content filter on the writer side.

Co-Authored-By: Tomoya Fujita <Tomoya.Fujita@sony.com>

## Contributor Checklist
- [x] Commit messages follow the project guidelines. 
- [x] The code follows the style guidelines of this project. 
- [x] Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added. 
- [x] Any new/modified methods have been properly documented using Doxygen. 
- [ ] Fast DDS test suite has been run locally. 
- [x] Changes are ABI compatible. 
- [x] Changes are API compatible. 
- [x] **WIP** Documentation builds and tests pass locally. 
- [ ] **WIP** New feature has been added to the `versions.md` file (if applicable).
- [x] **WIP** New feature has been documented/Current behavior is correctly described in the documentation. 

## Reviewer Checklist
- [x] Check contributor checklist is correct.
- [ ] Check CI results: changes do not issue any warning.
- [ ] Check CI results: failing tests are unrelated with the changes.

### CODE REVIEW

**Comment by MiguelCompany** [comment]
@fujitatomoya FYI

**Review by JLBuenoLopez-eProsima — APPROVED** [review]
LGTM with green CI

**Comment by JLBuenoLopez-eProsima** [comment]
Related Documentation PR: eProsima/Fast-DDS-docs#363

**Comment by EduPonz** [comment]
@richiprosima please test this

**Comment by MiguelCompany** [comment]
@richiprosima Please test this

**Comment by MiguelCompany** [comment]
@richiprosima Please test aarch64

**Pull request merged**
