### PR TITLE
Use ftruncate on QNX <master>

### LINKED ISSUE #1765: posix_fallocate does not work on shared memory on QNX
https://github.com/eProsima/Fast-DDS/blob/0149608645c53a563472f4cddd42d8980e38aa31/thirdparty/boost/include/boost/interprocess/shared_memory_object.hpp#L399

Is there a reason posix_fallocate() is used instead of ftruncate()? posix_fallocate returns an error code: "The fd argument doesn't refer to a regular file." which is due to that the file is a shared memory object and not an actual file.

Is there any drawbacks of using ftruncate instead?

### PR DESCRIPTION
**Pull request by MiguelCompany**
This should fix #1765

### CODE REVIEW

**Comment by MiguelCompany** [comment]
@richiprosima Please test this.

**Comment by richiprosima** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/3828/)
* Linux aarch64[Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux%20aarch64/985/)
* Mac [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/3369/)
* Windows [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/3854/)

**Comment by asobhy-qnx** [comment]
Can we add to 2.0.x and 2.1.x

**Comment by MiguelCompany** [comment]
> Can we add to 2.0.x and 2.1.x

We will cherry-pick after merging into master

**Comment by richiprosima** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/3829/)
* Linux aarch64[Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux%20aarch64/986/)
* Mac [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/3370/)
* Windows [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/3855/)

**Review by IkerLuengo — APPROVED** [review]
LGTM

**Pull request merged**
