### PR TITLE
fixed warnings [8886]

### PR DESCRIPTION
**Pull request by ahcorde**
There are a number of warning when I compile [performance_test](http://build.ros2.org/view/Fci/job/Fci__nightly-performance_ubuntu_focal_amd64/66/gcc/)

Most of them are related to `uint32_t` which this type corresponds with the literal `u` and not `ul`

Signed-off-by: ahcorde <ahcorde@gmail.com>

### CODE REVIEW

**Comment by dirk-thomas** [comment]
The CI failure seems to be unrelated to the patch. @richiware Please advise how to proceed.

**Comment by richiware** [comment]
@MiguelCompany  or @EduPonz . Would you help on this?

**Comment by ahcorde** [comment]
@MiguelCompany  thank you for the review :+1:

**Comment by ahcorde** [comment]
@MiguelCompany should we wait to run CI ?

**Comment by MiguelCompany** [comment]
> @MiguelCompany should we wait to run CI ?

It seems CI is having problems getting your code (see [here](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual/2498/console)), but I have just finished running it manually, and everything seemed fine, so merging this in.

**Pull request merged**
