### PR TITLE
Add Guid info to BasicConfiguration Example cout [15244] 

### PR DESCRIPTION
**Pull request by jparisu**
Signed-off-by: jparisu <javierparis@eprosima.com>

Add Guid info to BasicConfiguration Example in printed information by `cout`.

## Contributor Checklist
- [x] Commit messages follow the project guidelines. 
- [x] The code follows the style guidelines of this project. 
- *N/A* Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added. 
- *N/A* Any new/modified methods have been properly documented using Doxygen. 
- *N/A* Fast DDS test suite has been run locally. 
- [x] Changes are ABI compatible. 
- [x] Changes are API compatible. 
- *N/A* Documentation builds and tests pass locally. 
- *N/A* New feature has been added to the `versions.md` file (if applicable).
- *N/A* New feature has been documented/Current behavior is correctly described in the documentation. 

## Reviewer Checklist
- [x] Check contributor checklist is correct.
- [x] Check CI results: changes do not issue any warning.
- [x] Check CI results: failing tests are unrelated with the changes.

### CODE REVIEW

**Review by juanlofer-eprosima — CHANGES_REQUESTED** [review]
Suggestion:

- Add verbose argument to executable (`-v`) to print this additional information.
- Print message origin (Writer GUID) in verbose mode.

**Comment by MRicoIE2C** [comment]
LGTM

**Review by MRicoIE2C — APPROVED** [review]

**Comment by EduPonz** [comment]
@richiprosima please test this

**Comment by EduPonz** [comment]
@richiprosima please test this

**Pull request merged**
