### PR TITLE
Add XSD for static discovery [17842]

### PR DESCRIPTION
**Pull request by richiware**
## Description

This PR adds a new resources: an XSD file to validates static discovery XML files.

## Contributor Checklist
- [x] Commit messages follow the project guidelines. 
- [x] The code follows the style guidelines of this project. 
- [x] Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
- *N/A* Any new/modified methods have been properly documented using Doxygen. 
- [x] Changes are ABI compatible. 
- [x] Changes are API compatible. 
- [x] New feature has been added to the `versions.md` file (if applicable).
- *N/A* New feature has been documented/Current behavior is correctly described in the documentation. 
    
- *N/A* Applicable backports have been included in the description.

## Reviewer Checklist
- [x] The PR has a milestone assigned.
- [x] Check contributor checklist is correct.
- [x] Check CI results: changes do not issue any warning.
- [x] Check CI results: failing tests are unrelated with the changes.

### CODE REVIEW

**Review by JesusPoderoso — CHANGES_REQUESTED** [review]
It would be desirable to have the following milestones to merge this pull request:
- Install this schema as the profiles XSD done in `src/fastrtps/CMakeLists.txt` line 542
- Include system test as the profiles XSD done in `src/fastrtps/test/system/tools/fastdds/CMakeLists.txt` with all xml documents with the sufix `*_static_disc.xml`, and include it in the `tests.py` file
- 
Note: the CLI command `fastdds xml validate` would be used. It automatically uses the profiles schema, but adding `-x path/to/installed/static_discovery/schema.xsd` would validate the given `*_static_disc.xml` files against the given schema.

**Review by JLBuenoLopez-eProsima — CHANGES_REQUESTED** [review]
Blackbox tests include some XML files that require a previous CMake configuration (for instance `test/blackbox/PubSubreader_static_disc.xml.in`). It would be nice to configure and validate them as well.

**Comment by JesusPoderoso** [comment]
@richiprosima please test this

**Review by JLBuenoLopez-eProsima — DISMISSED** [review]
LGTM with green CI

**Review by JesusPoderoso — DISMISSED** [review]

**Pull request merged**
