### PR TITLE
[21470] Apply @Blast545 contribution: Add unsigned specification to literals (#5125)

### PR DESCRIPTION
**Pull request by JesusPoderoso**
## Description
This PR is a mimic of
- #5125 

which is opened by an eProsima Team member in order to run internal CI.
No tests are needed, but just the library build.
This fix may also be needed in the 2.10.x Iron version, so it is marked as a backportable PR.

@Mergifyio backport 2.10.x 

## Contributor Checklist

- [x] Commit messages follow the project guidelines. 
- [x] The code follows the style guidelines of this project. 
- **N/A** Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
- **N/A** Any new/modified methods have been properly documented using Doxygen. 
- **N/A** Any new configuration API has an equivalent XML API (with the corresponding XSD extension) 
- [x] Changes are backport compatible: they do **NOT** break ABI nor change library core behavior. 
- [x] Changes are API compatible. 
- **N/A** New feature has been added to the `versions.md` file (if applicable).
- **N/A** New feature has been documented/Current behavior is correctly described in the documentation. 
    
- [x] Applicable backports have been included in the description.

## Reviewer Checklist

- [x] The PR has a milestone assigned.
- [x] The title and description correctly express the PR's purpose.
- [x] Check contributor checklist is correct.
- **N/A** If this is a critical bug fix, backports to the critical-only supported branches have been requested.
- [x] Check CI results: changes do not issue any warning.
- [x] Check CI results: failing tests are unrelated with the changes.

### CODE REVIEW

**Review by Mario-DL — APPROVED** [review]
LGTM with green CI

**Review by Blast545 — APPROVED** [review]

**Comment by Blast545** [comment]
ping :pray:

**Comment by MiguelCompany** [comment]
@Blast545 Sorry for the delay. Vacations made this linger a bit

**Comment by MiguelCompany** [comment]
@Mergifyio backport 2.10.x

**Comment by MiguelCompany** [comment]
@mergifyio backport master

**Comment by Blast545** [comment]
Can I ask for this to also be backported to `2.6.x` as well? Since that's the one used for humble and we have the warnings appearing there :bow: 

Thanks in advance! @MiguelCompany

**Comment by JesusPoderoso** [comment]
@Mergifyio backport 2.6.x

**Pull request merged**
