### PR TITLE
Increase Keys example with disposing functionality [9205]

### PR DESCRIPTION
**Pull request by richiware**
This PR increases the Keys example (located on `examples/C++/Keys`). Now, at the end of the example, the writer disposes all keys and the reader waits until the dispose samples arrive.

### CODE REVIEW

**Comment by richiware** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/2535/)
* Mac [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/2346/)
* Windows [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/2542/)

**Review by IkerLuengo — CHANGES_REQUESTED** [review]
I know it is not the goal of the request, but can we the opportunity to change the `5` magic number to a const variable (even a define) for the number of instances? This `5` is referenced in many places and makes for poorly maintainable code.

**Review by IkerLuengo — APPROVED** [review]
LGTM

**Comment by richiware** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/2625/)
* Linux aarch64[Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux%20aarch64/42/)
* Mac [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/2441/)
* Windows [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/2635/)

**Comment by MiguelCompany** [comment]
This is only modifying an example, so tests are not affected. Merging in.

**Comment by MiguelCompany** [comment]
I didn't realize that this had warnings on windows 🤦 

@richiware Could you do a follow-up PR fixing them?

**Pull request merged**
