### PR TITLE
[20965] Fix Python Installation version in Github CI. Address failing system tests environment issues.

### PR DESCRIPTION
**Pull request by Mario-DL**
## Description

This PR addresses failing github CI system tests.

* It fixes Python installation version in Windows & Ubuntu Github CIs (macOs was already doing it).
* Selects the appropriate python version in the launcher used in `.bat` tool files by means of an environment variable `PYTHON_VERSION` {Major.Minor}.
* Prevents `Qt` from setting-up Python, as we are who manage the Python installation

_Notes:_ 
* In windows, `pywin32` is not listed as a required python package at the `Python Dependencies` step as it is a requirement of `colcon` and it is installed along with it.
* Python version is not fixed in the sanitizers jobs since system tests are not run there. 

Work done in #4731 precedes this PR.

@Mergifyio backport 2.13.x 2.10.x 2.6.x 

## Contributor Checklist

- [X] Commit messages follow the project guidelines. 
- [X] The code follows the style guidelines of this project. 
- _N/A_ Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
- _N/A_ Any new/modified methods have been properly documented using Doxygen. 
- _N/A_ Any new configuration API has an equivalent XML API (with the corresponding XSD extension) 
- _N/A_ Changes are ABI compatible. 
- _N/A_ Changes are API compatible. 
- _N/A_ New feature has been added to the `versions.md` file (if applicable).
- _N/A_ New feature has been documented/Current behavior is correctly described in the documentation. 
    
- [X] Applicable backports have been included in the description.

## Reviewer Checklist

- [x] The PR has a milestone assigned.
- [x] The title and description correctly express the PR's purpose.
- [x] Check contributor checklist is correct.
- [x] Check CI results: changes do not issue any warning.
- [x] Check CI results: failing tests are unrelated with the changes.

### CODE REVIEW

**Review by JesusPoderoso — APPROVED** [review]
LGTM with green CI

**Comment by JesusPoderoso** [comment]
@richiprosima please test this

**Review by JesusPoderoso — DISMISSED** [review]
LRGTM!
Great job @Mario-DL! 🎉

**Review by JesusPoderoso — APPROVED** [review]

**Comment by EduPonz** [comment]
@Mergifyio backport 2.13.x 2.10.x 2.6.x

**Pull request merged**
