### PR TITLE
[17513] Add nightly Ubuntu Github CI

### PR DESCRIPTION
**Pull request by EduPonz**
## Description

This PR adds:

* [x] A reusable workflow for Ubuntu CI
* [x] A nightly workflow for Ubuntu CI in 22.04

Should be merged after:

* #4447
* #4448

TODO:

* [x] Drop testing commit that enables testing on push to branch

## Contributor Checklist

- [x] Commit messages follow the project guidelines. 
- *N/A*: The code follows the style guidelines of this project. 
- *N/A*: Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
- *N/A*: Any new/modified methods have been properly documented using Doxygen. 
- *N/A*: Changes are ABI compatible. 
- *N/A*: Changes are API compatible. 
- *N/A*: New feature has been added to the `versions.md` file (if applicable).
- *N/A*: New feature has been documented/Current behavior is correctly described in the documentation. 
    
- *N/A*: Applicable backports have been included in the description.

## Reviewer Checklist

- [x] The PR has a milestone assigned.
- [x] Check contributor checklist is correct.
- [x] Check CI results: changes do not issue any warning.
- [x] Check CI results: failing tests are unrelated with the changes.

### CODE REVIEW

**Comment by EduPonz** [comment]
@Mergifyio backport 2.12.x 2.11.x 2.10.x 2.6.x

**Comment by JesusPoderoso** [comment]
@Mergifyio backport 2.13.x

**Comment by JesusPoderoso** [comment]
This test `BlackboxTests_DDS_PIM.Discovery.ServerClientEnvironmentSetUpDNS` seems to fail in both Ubuntu, Mac and sanitizer cases

**Comment by EduPonz** [comment]
> This test `BlackboxTests_DDS_PIM.Discovery.ServerClientEnvironmentSetUpDNS` seems to fail in both Ubuntu, Mac and sanitizer cases

It makes sense that it fails, as the DNS is not configured. What I don't understand yet is why it runs in the first place, specially given:

https://github.com/eProsima/Fast-DDS/blob/31a83ca619fce97f7c4a0cae2ea482f5e4929157/test/blackbox/CMakeLists.txt#L54

**Review by JesusPoderoso — APPROVED** [review]
LRGTM! 🥹

**Review by JesusPoderoso — APPROVED** [review]

**Pull request merged**
