### PR TITLE
Fix data_count = 0 when using datasharing [16060]

### PR DESCRIPTION
**Pull request by irenebm**
Signed-off-by: Irene Bandera <irenebandera@eprosima.com>

## Contributor Checklist
- [x] Commit messages follow the project guidelines. 
- [x] The code follows the style guidelines of this project. 
- *N/A* Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added. 
- *N/A* Any new/modified methods have been properly documented using Doxygen. 
- [x] Fast DDS test suite has been run locally. 
- [x] Changes are ABI compatible. 
- [x] Changes are API compatible. 
- [x] Documentation builds and tests pass locally. 
- *N/A* New feature has been added to the `versions.md` file (if applicable).
- *N/A* New feature has been documented/Current behavior is correctly described in the documentation. 

## Reviewer Checklist
- [x] Check contributor checklist is correct.
- [x] Check CI results: changes do not issue any warning.
- [x] Check CI results: failing tests are unrelated with the changes.

### CODE REVIEW

**Review by jparisu — COMMENTED** [review]
Looks good.
However, I think this really needs to be documented somewhere, public or private. Otherwise we would continue to come to this doubt again.

**Review by MiguelCompany — APPROVED** [review]

**Comment by MiguelCompany** [comment]
@mergifyio rebase

**Comment by MiguelCompany** [comment]
@richiprosima Please test this

**Comment by Mario-DL** [comment]
@richiprosima please test windows

**Comment by JLBuenoLopez-eProsima** [comment]
@Mergifyio backport 2.10.x 2.9.x 2.6.x

**Pull request merged**
