### PR TITLE
Apply setting subscriber's partition to empty set [12317]

### LINKED ISSUE #2107: Changing Partition QoS on running Publisher and Subscriber has no affect [12315]
I have a a Participant with different publishers and subscribers. The publishers have a initial partition, while the subscribers should change the partition on runtime. This should filter data on sending side. How can i solve this problem?

subscriber.set_qos() has no affect on running subscribers. Or is there a refresh mechanism i did not use?

### PR DESCRIPTION
**Pull request by EduPonz**
Fixes #2107 

- [x] Fix
- [x] Regression tests

Signed-off-by: Eduardo Ponz Segrelles <eduardoponz@eprosima.com>

### CODE REVIEW

**Review by MiguelCompany — DISMISSED** [review]
LGTM

**Review by MiguelCompany — APPROVED** [review]
LGTM

**Review by MiguelCompany — CHANGES_REQUESTED** [review]
* Fix warning on windows
* Discovery server `test_34_connect_locally_with_remote_server` failure is unusual

**Comment by EduPonz** [comment]
* I think I've address the Windows warnings in 80f5f1c.
* Failure of `test_34_connect_locally_with_remote_server` seems totally unrelated. Additionally, [in the CI run for](http://jenkins.eprosima.com:8080/job/discovery_server_linux/945/consoleFull) 727c839 the test passed, as well as locally for me

**Review by MiguelCompany — APPROVED** [review]
LGTM, but CI should be re-run after merging #1996

**Comment by EduPonz** [comment]
@mergifyio rebase 2.0.x 2.1.x 2.2.x 2.3.x

**Comment by EduPonz** [comment]
@Mergifyio backport 2.0.x 2.1.x 2.2.x 2.3.x

**Comment by MiguelCompany** [comment]
@richiprosima Please test this

**Pull request merged**
