### PR TITLE
[14260] Fixed exported symbols on ContentFilteredTopic

### PR DESCRIPTION
**Pull request by MiguelCompany**
## Description

This PR fixes the exported symbols on ContentFilteredTopic

## Contributor Checklist
- [x] Commit messages follow the project guidelines. 
- [x] The code follows the style guidelines of this project. 
- *N/A* Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added. 
- *N/A* Any new/modified methods have been properly documented using Doxygen. 
- *N/A* Fast DDS test suite has been run locally. 
- Changes are **NOT** ABI compatible. 
- [x] Changes are API compatible. 
- [x] Documentation builds and tests pass locally. 
- [x] New feature has been added to the `versions.md` file (if applicable).
- [x] *N/A* New feature has been documented/Current behavior is correctly described in the documentation. 

## Reviewer Checklist
- [ ] Check contributor checklist is correct.
- [ ] Check CI results: changes do not issue any warning.
- [ ] Check CI results: failing tests are unrelated with the changes.

### CODE REVIEW

**Review by JLBuenoLopez-eProsima — DISMISSED** [review]
LGTM

**Comment by MiguelCompany** [comment]
@richiprosima Please test this

**Comment by MiguelCompany** [comment]
@richiprosima Please test windows

**Comment by MiguelCompany** [comment]
@JLBuenoLopez-eProsima I rebased this one and updated `versions.md`

**Review by JLBuenoLopez-eProsima — APPROVED** [review]
LGTM

**Pull request merged**
