### PR TITLE
[20583] DataReader::return_loan returns OK on loanable sequences without loans

### PR DESCRIPTION
**Pull request by EduPonz**
## Description

With this PR, `DataReader::return_loan` starts returning OK when given a loanable sequence with no loans, i.e.;
1. A loanable sequence with a set maximum (no loans are performed)
2. A empty loanable sequence

**IMPORTANT**: Even though these changes are API and ABI compatible, this a behavioral change and cannot target a patch release.

## Contributor Checklist
- [x] Commit messages follow the project guidelines. 
- [x] The code follows the style guidelines of this project. 
- [x] Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
- [x] Any new/modified methods have been properly documented using Doxygen. 
- [x] Changes are ABI compatible. 
- [x] Changes are API compatible. 
- [x] New feature has been added to the `versions.md` file (if applicable).
- [x] New feature has been documented/Current behavior is correctly described in the documentation. 
    
- _N/A_; Applicable backports have been included in the description.

## Reviewer Checklist

- [x] The PR has a milestone assigned.
- [x] The title and description correctly express the PR's purpose.
- [x] Check contributor checklist is correct.
- [x] Check CI results: changes do not issue any warning.
- [x] Check CI results: failing tests are unrelated with the changes.

### CODE REVIEW

**Comment by EduPonz** [comment]
@richiprosima please test_3 this

**Review by Mario-DL — APPROVED** [review]
LGTM, as soon as we rebase this time and run ci we should merge to avoid further conflicts

**Review by Mario-DL — APPROVED** [review]
LGTM with green CI

**Review by Mario-DL — APPROVED** [review]
LGTM with green Windows CI

**Pull request merged**
