### PR TITLE
[20391] Migrate communication tests

### PR DESCRIPTION
**Pull request by elianalf**
## Description

This pr migrates `test/communication` tests into `test/dds/communication` folder, which use the new APIs rather than the old ones of fastrtps

## Contributor Checklist
- [x] Commit messages follow the project guidelines. 
- [x] The code follows the style guidelines of this project. 
- [x] Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
- [x] Any new/modified methods have been properly documented using Doxygen. 
- N/A Changes are ABI compatible. 
- N/A Changes are API compatible. 
- [x] New feature has been added to the `versions.md` file (if applicable).
- N/A New feature has been documented/Current behavior is correctly described in the documentation. 
    
- N/A Applicable backports have been included in the description.

## Reviewer Checklist
- [x] The PR has a milestone assigned.
- [x] The title and description correctly express the PR's purpose.
- [x] Check contributor checklist is correct.
- [x] Check CI results: changes do not issue any warning.
- [x] Check CI results: failing tests are unrelated with the changes.

### CODE REVIEW

**Review by EduPonz — DISMISSED** [review]

**Review by EduPonz — APPROVED** [review]
LGTM with green CI

**Comment by EduPonz** [comment]
@richiprosima please test this

**Comment by JesusPoderoso** [comment]
@richiprosima please test mac

**Comment by EduPonz** [comment]
@elianalf I'm afraid we'll need to look into the test failures in the MacOS Jenkins job before we can merge this

**Comment by EduPonz** [comment]
@richiprosima please test this

**Pull request merged**
