### PR TITLE
[21924] Roadmap update

### PR DESCRIPTION
**Pull request by MiguelCompany**
## Description

This PR updates the roadmap with cool ideas for the future development of Fast DDS.

## Contributor Checklist

- [x] Commit messages follow the project guidelines. 
- _N/A_: The code follows the style guidelines of this project. 
- _N/A_: Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
- _N/A_: Any new/modified methods have been properly documented using Doxygen. 
- _N/A_: Any new configuration API has an equivalent XML API (with the corresponding XSD extension) 
- _N/A_: Changes are backport compatible: they do **NOT** break ABI nor change library core behavior. 
- _N/A_: Changes are API compatible. 
- _N/A_: New feature has been added to the `versions.md` file (if applicable).
- _N/A_: New feature has been documented/Current behavior is correctly described in the documentation. 
    
- _N/A_: Applicable backports have been included in the description.

## Reviewer Checklist

- [x] The PR has a milestone assigned.
- [x] The title and description correctly express the PR's purpose.
- [x] Check contributor checklist is correct.
- _N/A_: If this is a critical bug fix, backports to the critical-only supported branches have been requested.
- _N/A_: Check CI results: changes do not issue any warning.
- _N/A_: Check CI results: failing tests are unrelated with the changes.

### CODE REVIEW

**Comment by Mario-DL** [comment]
Cool additions.
It would be also interesting making `PropertyPolicyQos` mutable in the mid/long term, what do you think ?

**Comment by MiguelCompany** [comment]
> Cool additions. It would be also interesting making `PropertyPolicyQos` mutable in the mid/long term, what do you think ?

I think it is better to transform some/all of [these](https://fast-dds.docs.eprosima.com/en/latest/fastdds/property_policies/property_policies.html) into proper QoS.
We could then decide which of them should be mutable

**Review by Mario-DL — APPROVED** [review]
LGTM

**Comment by richiware** [comment]
It would be great to have the ability to output statistics through a different interface than user data.

**Comment by richiware** [comment]
Also I it would be great to have TypeAssignability

**Review by rsanchez15 — APPROVED** [review]

**Review by Mario-DL — APPROVED** [review]

**Review by richiware — APPROVED** [review]

**Pull request merged**
