### PR TITLE
[17294] Honor allow_unauthenticated_participants flag

### PR DESCRIPTION
**Pull request by Mario-DL**
## Description

This PR introduces the compliant behavior of `allow_unauthenticated_participants`, defined in the governance file.

Premises according to [DDS Security](https://www.omg.org/spec/DDS-SECURITY/):
1) If there is no matching topic rule for a topic, the entity creation must fail (which is the current behavior).
2) If `<rtps_protection_kind>`  is not `NONE` and `allow_unauthenticated_participants` is set to `TRUE`, entity must fail with error.
3) Topics protected with `is_write_protected` and `is_read_protected` should not be able to communicate regardless of the allow_unauthenticated_participants flag (8.8.7.1 AccessControl behavior with discovered endpoints from “Unauthenticated” DomainParticipant)
4) Despite `allow_unauthenticated_participants` is set to true, try always to authenticate first.
5) For any matched “Unauthenticated” DomainParticipant entities, the DomainParticipant
shall match only the regular builtin Endpoints (ParticipantMessage, DCPSParticipants,
DCPSPublications, DCPSSubscriptions) and not the builtin secure Endpoints (see 7.4.5 for the complete list).
6) Assume the DDS implementation transitioned to the HandshakeMessageSend state, sent the message M1 and is now in the HandshakeMessageWait state waiting for the reply. If no reply is received within an implementation-specific retry-time, the same
message M1 shall be sent again and the process repeated _until either a reply is received or an implementation-specific timeout elapses (or a maximum number of retries is reached)_

>NOTE: Feature has been tested on Simple Discovery for the moment. Proper testing on Discovery Server should be done in the future.

@Mergifyio backport 2.10.x 2.9.x 2.6.x 2.1.x

## Contributor Checklist
- [X] Commit messages follow the project guidelines. 
- [X] The code follows the style guidelines of this project. 
- [X] Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
- [X] Any new/modified methods have been properly documented using Doxygen. 
- [X] Changes are ABI compatible. 
- [X] Changes are API compatible. 
- **N/A** New feature has been added to the `versions.md` file (if applicable).
- [X] New feature has been documented/Current behavior is correctly described in the documentation. 
   Related documentation PR: eProsima/Fast-DDS-docs#477
- [X] Applicable backports have been included in the description.

## Reviewer Checklist
- [ ] The PR has a milestone assigned.
- [ ] Check contributor checklist is correct.
- [ ] Check CI results: changes do not issue any warning.
- [ ] Check CI results: failing tests are unrelated with the changes.

### CODE REVIEW

**Comment by Mario-DL** [comment]
@richiprosima please test uncrustify

**Comment by Mario-DL** [comment]
@richiprosima please test uncrusitfy

**Comment by Mario-DL** [comment]
@richiprosima please test github_uncrustify

**Comment by Mario-DL** [comment]
@richiprosima please test this

**Comment by Mario-DL** [comment]
@richiprosima please test this

**Comment by Mario-DL** [comment]
@richiprosima please test this

**Review by jsantiago-eProsima — CHANGES_REQUESTED** [review]
I think there are some functionalities required by the DDS Security standard that are not being properly tested:

- Topics protected with **is_write_protected** and **is_read_protected** should not be able to communicate regardless of the `allow_unauthenticated_participants` flag (8.8.7.1 AccessControl behavior with discovered endpoints from “Unauthenticated” DomainParticipant)
- Two participants with the same GUID may have different security configuration. In this case, the one with the valid credential overrides the matching of the Unauthenticated one. (Table 27 – Description of the ParticipantSecurityAttributes)

**Comment by Mario-DL** [comment]
Implemented the first suggested scenario regarding `is_read_protected` and `is_write_protected` flags.

For further follow up with the premise:
_Two participants with the same GUID may have different security configuration_
Find the corresponding test here [allow_unauth_same_guid.txt](https://github.com/eProsima/Fast-DDS/files/11429227/allow_unauth_same_guid.txt)
Hints for the implementation:

- When the initial secure participant recevies the discovery `Data[P]`change of the late-joined secure Participant, it discards it because of having a lower SequenceNumber (because it had previously matched a non-secure participant with the same `GUID_t`). A possible workaround for that would be forcing a secure enabled participant to unmatch a previously known non-secure participant in both PDP and EDP builtin readers.

**Comment by Mario-DL** [comment]
@richiprosima please test this

**Comment by Mario-DL** [comment]
@richiprosima please test this

**Comment by Mario-DL** [comment]
@richiprosima please test this

**Review by jsantiago-eProsima — APPROVED** [review]
CI Issues seem unrelated. Approved.

**Comment by MiguelCompany** [comment]
@Mergifyio backport 2.10.x 2.9.x 2.6.x 2.1.x

**Pull request merged**
