### PR TITLE
 Garbage collect remote SHM segments when origin Participant is closed / dead <master> [8607]

### PR DESCRIPTION
**Pull request by adolfomarver**
When a SHM listener receives a message from an origin, the origin SHM segment is opened to read the message. The segment is kept open in order to read next messages from the same origin. But when the origin is closed the segment is not closed by the listener so the memory is not freed.

This PR adds the following feature:

* Remote SHM segments are watched by the SharedMemWatchdog to be closed when the origin segment has been closed or is in zombie state.

### CODE REVIEW

**Comment by richiware** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/2157/)
* Mac [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/1947/)
* Windows [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/2152/)

**Comment by richiware** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/2158/)
* Mac [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/1948/)
* Windows [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/2153/)

**Comment by richiware** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/2162/)
* Mac [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/1952/)
* Windows [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/2157/)

**Comment by adolfomarver** [comment]
ROS2-CI Tests, with SHM default enabled, in Linux Docker passes with the same errors as with UDP only.
Now /dev/shm is nerver occupied more than 15% over the whole CI process. 

Still to do:
* Add unit tests.
* This method implies every process has a thread (Watchdog) iterating, every second, through all opened remote segments checking (in the file system) whether the segment is alive. @MiguelCompany I would like to dicuss with you improvements to this algorithm, I think the rate of checking should be limited, a process like the ROS2 Daemon may have lots of segments opened and check all every second seems to me an unnecessary overload, more over, the checking implies throwing some std::exceptions that alloc std::strings, this should be also change to an allocation free mechanishm.

**Comment by richiware** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/2168/)
* Mac [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/1958/)
* Windows [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/2163/)

**Comment by richiware** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/2176/)
* Mac [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/1966/)
* Windows [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/2171/)

**Comment by adolfomarver** [comment]
Tested in ROS2-CI Docker.

**Comment by richiware** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/2314/)
* Mac [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/2114/)
* Windows [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/2306/)

**Comment by richiware** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/2315/)
* Mac [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/2115/)
* Windows [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/2307/)

**Pull request merged**
