### PR TITLE
[15155] Fixed validation on ParameterPropertyList_t

### PR DESCRIPTION
**Pull request by MiguelCompany**
Signed-off-by: Miguel Company <MiguelCompany@eprosima.com>

## Description

A parameter on a parameter list should not be considered invalid if its length is greater than expected.
This should fix interoperability issues like [this one](https://github.com/eclipse-cyclonedds/cyclonedds/issues/1328)

Draft till we add a test

@Mergifyio backport 2.6.x

## Contributor Checklist
- [x] Commit messages follow the project guidelines. 
- [x] The code follows the style guidelines of this project. 
- [x] Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added. 
- *N/A* Any new/modified methods have been properly documented using Doxygen. 
- [x] Fast DDS test suite has been run locally. 
    - [x] Only the new test has been run
- [x] Changes are ABI compatible. 
- [x] Changes are API compatible. 
- *N/A* Documentation builds and tests pass locally. 
- *N/A* New feature has been added to the `versions.md` file (if applicable).
- *N/A* New feature has been documented/Current behavior is correctly described in the documentation. 

## Reviewer Checklist
- [ ] Check contributor checklist is correct.
- [ ] Check CI results: changes do not issue any warning.
- [ ] Check CI results: failing tests are unrelated with the changes.

### CODE REVIEW

**Comment by MiguelCompany** [comment]
@richiprosima Please test this

**Comment by MiguelCompany** [comment]
@richiprosima Please test mac

**Comment by k7g03z** [comment]
@MiguelCompany I tested this branch with the following set up:
Docker1: ROS2 Rolling, with Fast-DDS checkout out to this branch, Micro-ROS Linux docker with ROS2 Agent, Ping App
Docker2: ROS2 Galactic with CycloneDDS
Both dockers are connected by virtual network
MicroROS Ping app sends pings through XRCE to the ROS2 Agent, then converter to DDS with `fastrtps`.
Docker2 can show topics with `ros2 topic list` and `ros2 topic echo /MicroRos/ping`

Before this fix , this was not possible. Thanks for the quick fix!

cc @sumanth-nirmal

**Review by richiware — APPROVED** [review]

**Comment by MiguelCompany** [comment]
@mergifyio backport 2.6.x

**Comment by MiguelCompany** [comment]
@mergifyio backport 2.3.x 2.1.x

**Pull request merged**
