### PR TITLE
Remove getGuid implementation in StatefulReader mock

### PR DESCRIPTION
**Pull request by rsanchez15**
## Contributor Checklist
- [x] Commit messages follow the project guidelines. 
- [x] The code follows the style guidelines of this project. 
- [x] Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added. 
- [x] Any new/modified methods have been properly documented using Doxygen. 
- [x] Fast DDS test suite has been run locally. 
- [x] Changes are ABI compatible. 
- [x] Changes are API compatible. 
- [x] Documentation builds and tests pass locally. 
- [ ] New feature has been added to the `versions.md` file (if applicable).
- [ ] New feature has been documented/Current behavior is correctly described in the documentation. 

## Reviewer Checklist
- [x] Check contributor checklist is correct.
- [ ] Check CI results: changes do not issue any warning.
- [ ] Check CI results: failing tests are unrelated with the changes.

### CODE REVIEW

**Comment by rsanchez15** [comment]
@richiprosima Please test this

**Review by juanlofer-eprosima — APPROVED** [review]
LGTM, failing tests seem unrelated (merger please verify)

**Comment by EduPonz** [comment]
@richiprosima please test mac

**Comment by JLBuenoLopez-eProsima** [comment]
@richiprosima Please test mac again

**Review by JLBuenoLopez-eProsima — APPROVED** [review]
LGTM!

CI failures are unrelated

**Pull request merged**
