### PR TITLE
[20118] Fix Monitor Service types & test without security

### PR DESCRIPTION
**Pull request by Mario-DL**
## Description

This PR regenerates monitor service types with Fast DDS Gen `3.1.0`, updates the corresponding `CMakeLists.txt` and moves a source file for correcting a compilation issue when compiling the monitor service with `SECURITY=OFF`

## Contributor Checklist
- [X] Commit messages follow the project guidelines. 
- [X] The code follows the style guidelines of this project. 
- **N/A** Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
- **N/A** Any new/modified methods have been properly documented using Doxygen. 
- [X] Changes are ABI compatible. 
- [X] Changes are API compatible. 
-  **N/A** New feature has been added to the `versions.md` file (if applicable).
-  **N/A** New feature has been documented/Current behavior is correctly described in the documentation. 
    
-  **N/A** Applicable backports have been included in the description.

## Reviewer Checklist
- [x] The PR has a milestone assigned.
- [x] Check contributor checklist is correct.
- [x] Check CI results: changes do not issue any warning.
- [x] Check CI results: failing tests are unrelated with the changes.

### CODE REVIEW

**Comment by Mario-DL** [comment]
Backwards compatibility run here: https://github.com/eProsima/Fast-DDS-python/actions/runs/7179607420/job/19550139342

**Comment by EduPonz** [comment]
@richiprosima please test mac

**Comment by EduPonz** [comment]
@richiprosima please test this

**Review by JesusPoderoso — APPROVED** [review]
LGTM with green CI

**Pull request merged**
