### PR TITLE
DomainParticipantFactory lookup_participant

### PR DESCRIPTION
**Pull request by laura-eprosima**
* New unit tests for PIM lookup_participant method
* Implementation of PSM correspondence method (find)
* New unit tests for PSM find method

NOTE: This PR must be merged after #1073

### CODE REVIEW

**Comment by richiware** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/1608/)
* Mac [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/1374/)
* Windows [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/1604/)

**Comment by richiware** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/1626/)
* Mac [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/1392/)
* Windows [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/1622/)

**Comment by laura-eprosima** [comment]
> Looks like file `include/dds/core/xtypes/Annotation.hpp.autosave` was added to the repo by mistake on commit [4b72d8c](https://github.com/eProsima/Fast-RTPS/commit/4b72d8ce64cb93094ce68d651677da4149e68d45). But without that file the commit would be empty.
> 
> Is there some other change missing on that commit, or can it be removed altogether?

It is a mistake due to a change I made later on PR #1073, which makes that commit to become empty.

**Comment by richiware** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/1646/)
* Mac [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/1412/)
* Windows [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/1642/)

**Pull request closed without merging**
