### PR TITLE
[18431] Fix missing includes

### LINKED ISSUE #3494: Missing cstdint includes (TypeNamesGenerator.h, TransportDescriptorInterface.h)
### Is there an already existing issue for this?

- [X] I have searched the existing issues

### Expected behavior

The following files are missing includes to cstdint
```
eProsima/Fast-DDS/include/fastrtps/types/TypeNamesGenerator.h
eProsima/Fast-DDS/include/fastdds/rtps/transport/TransportDescriptorInterface.h
```

### Current behavior

Fails to build

### Steps to reproduce

Build with GCC 13.1.1

### Fast DDS version/commit

master

### Platform/Architecture

Other. Please specify in Additional context section.

### Transport layer

Default configuration, UDPv4 & SHM

### Additional context

ROS2 humble 2023.05.02 patch release

### XML configuration file

_No response_

### Relevant log output

_No response_

### Network traffic capture

_No response_

### PR DESCRIPTION
**Pull request by JLBuenoLopez-eProsima**
## Description

@Mergifyio backport 2.9.x 2.6.x 2.1.x

Fixes #3494

## Contributor Checklist
- [x] Commit messages follow the project guidelines. 
- [x] The code follows the style guidelines of this project. 
- [N/A] Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
- [N/A] Any new/modified methods have been properly documented using Doxygen. 
- [x] Changes are ABI compatible. 
- [x] Changes are API compatible. 
- [N/A] New feature has been added to the `versions.md` file (if applicable).
- [N/A] New feature has been documented/Current behavior is correctly described in the documentation. 
    
- [x] Applicable backports have been included in the description.

## Reviewer Checklist
- [x] The PR has a milestone assigned.
- [x] Check contributor checklist is correct.
- [ ] Check CI results: changes do not issue any warning.
- [ ] Check CI results: failing tests are unrelated with the changes.

### CODE REVIEW

**Review by MiguelCompany — DISMISSED** [review]
LGTM with green build

**Comment by JLBuenoLopez-eProsima** [comment]
@richiprosima please test this

**Review by MiguelCompany — APPROVED** [review]

**Comment by skrede** [comment]
Could this change be made to 2.10.x as well? In its current state, this prevents ROS2 from building on systems with GCC 13.1, as ROS2 specifically targets the 2.10.x branch. 

https://github.com/ros2/ros2/blob/rolling/ros2.repos

**Comment by MiguelCompany** [comment]
@skrede It is already in 2.10.x: commit https://github.com/eProsima/Fast-DDS/commit/add29f42591fe3d785df727aea128f250040834f

**Comment by JLBuenoLopez-eProsima** [comment]
@Mergifyio backport 2.9.x 2.6.x

**Comment by indeedhat** [comment]
Could this get back ported to 2.6.4 as required by ros2 humble-release please

**Comment by JLBuenoLopez-eProsima** [comment]
@indeedhat, these changes have already been backported into 2.6.x in #3518. These changes will be included in the next patch release: 2.6.5. Until that moment, just build using 2.6.x branch or the commit that introduces the changes 02539b9. Fast DDS policy is not to change published releases.

**Comment by kistlin** [comment]
I think the same happens in the latest release v2.11.0, when building the statistics backend.

To fix it, the following change was necessary.
```
diff --git a/include/fastdds/dds/core/status/StatusMask.hpp b/include/fastdds/dds/core/status/StatusMask.hpp
index c838ff369..2718869d7 100644
--- a/include/fastdds/dds/core/status/StatusMask.hpp
+++ b/include/fastdds/dds/core/status/StatusMask.hpp
@@ -24,6 +24,7 @@
 #include <fastrtps/fastrtps_dll.h>

 #include <bitset>
+#include <cstdint>
 #include <sstream>

 //!Alias of size_t(16)
```

**Pull request merged**
