### PR TITLE
Fix cmake_minimum_required due to target_link_options [15378]

### PR DESCRIPTION
**Pull request by richiware**
## Description

There is being used `target_link_options` in our CMakeLists.txt files which was incorporated in CMake 3.13. This PR
fixes the `cmake_minimum_required`.

## Contributor Checklist
- [x] Commit messages follow the project guidelines. 
- [x] The code follows the style guidelines of this project. 
- [ ] Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added. 
- [ ] Any new/modified methods have been properly documented using Doxygen. 
- [ ] Fast DDS test suite has been run locally. 
- [ ] Changes are ABI compatible. 
- [ ] Changes are API compatible. 
- [ ] Documentation builds and tests pass locally. 
- [ ] New feature has been added to the `versions.md` file (if applicable).
- [ ] New feature has been documented/Current behavior is correctly described in the documentation. 

## Reviewer Checklist
- [ ] Check contributor checklist is correct.
- [ ] Check CI results: changes do not issue any warning.
- [ ] Check CI results: failing tests are unrelated with the changes.

### CODE REVIEW

**Comment by richiware** [comment]
@Mergifyio backport 2.3.x

**Review by jsantiago-eProsima — APPROVED** [review]
LGTM

**Comment by richiware** [comment]
@richiprosima Please test mac

**Comment by richiware** [comment]
@richiprosima Please test mac

**Pull request merged**
