### PR TITLE
Move TypeDescriptor::stateTable from header to implementation. [11841]

### PR DESCRIPTION
**Pull request by MiguelCompany**
Just what the title says.

Related to #2014

### CODE REVIEW

**Comment by MiguelCompany** [comment]
@mergifyio rebase

**Comment by MiguelCompany** [comment]
@mergifyio rebase

**Review by richiware — APPROVED** [review]

**Comment by MiguelCompany** [comment]
Unrelated failures.

**Comment by richiware** [comment]
Failed tests not related.

**Pull request merged**
