### PR TITLE
Endianness macro [9189]

### PR DESCRIPTION
**Pull request by EduPonz**
This PR substitutes the definition we were making of `__BIG_ENDIAN__` for `FASTDDS_IS_BIG_ENDIAN_TARGET`. This way, we avoid using compiler reserved notation, and also defining a macro that some other libraries like boost do not expect to have defined when the machine is little endian. Furthermore, it updates the Fast CDR submodule to the [v1.0.15 release](https://github.com/eProsima/Fast-CDR/releases/tag/v1.0.15).

This PR solves #1001

### CODE REVIEW

**Review by MiguelCompany — CHANGES_REQUESTED** [review]
Please fix uncrustify issues

**Comment by richiware** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/2513/)
* Mac [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/2326/)
* Windows [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/2520/)

**Comment by richiware** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/2521/)
* Mac [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/2334/)
* Windows [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/2528/)

**Review by MiguelCompany — CHANGES_REQUESTED** [review]
I think we should take the chance to refactor the code and improve readability.

**Review by MiguelCompany — APPROVED** [review]

**Pull request merged**
