### PR TITLE
Bugfix: LifespanQoSExample Using the api incorrectly

### PR DESCRIPTION
**Pull request by zekai-li**
…simultaneously

LifespanQoSExample Use read_next_sample and take_next_sample simultaneously

## Description
  LifespanQoSExample Using the api incorrectly,Incorrect read_next_sample and take_next_sample are used at the same time, resulting in the failure to read historical data during the life cycle.

## Contributor Checklist

- [ ] Commit messages follow the project guidelines. 
- [ ] The code follows the style guidelines of this project. 
- [ ] Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
- [ ] Any new/modified methods have been properly documented using Doxygen. 
- [ ] Any new configuration API has an equivalent XML API (with the corresponding XSD extension) 
- [ ] Changes are backport compatible: they do **NOT** break ABI nor change library core behavior. 
- [ ] Changes are API compatible. 
- [ ] New feature has been added to the `versions.md` file (if applicable).
- [ ] New feature has been documented/Current behavior is correctly described in the documentation. 
    
- [ ] Applicable backports have been included in the description.

## Reviewer Checklist

- [ ] The PR has a milestone assigned.
- [ ] The title and description correctly express the PR's purpose.
- [ ] Check contributor checklist is correct.
- [ ] Check CI results: changes do not issue any warning.
- [ ] Check CI results: failing tests are unrelated with the changes.

### CODE REVIEW

**Comment by JesusPoderoso** [comment]
Hi @zekai-li, thanks for your contribution.
All the examples are being refactored, as part of the preparation for the following Fast DDS v3.0.0 release.
This example in particular has been condensed in the [configuration example](https://github.com/eProsima/Fast-DDS/blob/master/examples/cpp/configuration/README.md).
Therefore introducing these `loans` changes in the example does not make sense, even for 2.14.x. There will be a specific example using `loans` in v3.0.0 too.

**Comment by zekai-li** [comment]
> 你好@zekai-li，感谢您的贡献。 所有示例都正在重构，作为为下一个 Fast DDS v3.0.0 版本做准备的一部分。 这个例子在[配置示例](https://github.com/eProsima/Fast-DDS/blob/master/examples/cpp/configuration/README.md)中被特别压缩了。 因此，在示例中引入这些更改是没有意义的，即使对于 2.14.x 也是如此。在 v3.0.0 中`loans`也会有一个使用的特定示例。`loans`
I see. Is there a todo list in the v3.0 refactoring? I want to try to submit pr for this project. Also, I think lifespan, deadline, and other fine-grained examples are better for beginners to understand fastdds, which is why I fixed this bug in the first place. Do you want me to add more fine-grained examples to the example?

**Comment by zekai-li** [comment]
> Hi @zekai-li, thanks for your contribution. All the examples are being refactored, as part of the preparation for the following Fast DDS v3.0.0 release. This example in particular has been condensed in the [configuration example](https://github.com/eProsima/Fast-DDS/blob/master/examples/cpp/configuration/README.md). Therefore introducing these `loans` changes in the example does not make sense, even for 2.14.x. There will be a specific example using `loans` in v3.0.0 too.

I see. Is there a todo list in the v3.0 refactoring? I want to try to submit pr for this project. Also, I think lifespan, deadline, and other fine-grained examples are better for beginners to understand fastdds, which is why I fixed this bug in the first place. Do you want me to add more fine-grained examples to the example?

**Comment by zekai-li** [comment]
@JesusPoderoso I see. Is there a todo list in the v3.0 refactoring? I want to try to submit pr for this project. thanks

**Comment by JesusPoderoso** [comment]
Hi @zekai-li! 
The list of pending changes is not public, but these are the new requirements for the examples refactor in case you want to contribute to their improvement (also you can take the following pull requests into account as a reference: #4547, #4570, #4836, #4889, #4859, #4913):
- remove the DDS prefix from the binaries
- snake case in binary names and directory names
- take all examples out of the `dds` folder 
- launch only one endpoint per binary (always running them in different shells)
- unify args names and utility
- follow new Application architecture (Application, PublisherApp, SubscriberApp)...
- write proper README.md with the purpose of the example and expected inputs, outputs, behavior…
- implement listener callback in the same class (inheritance)
- include initialization (`init()`) methods in the constructors, and remove existing `init()` methods
- improve parsing options to be a black box to the user

You can start with the [RequestReplyExample](https://github.com/eProsima/Fast-DDS/tree/master/examples/cpp/dds/RequestReplyExample), which should be renamed to `request_reply`, or with the [SecureHelloWorldExample](https://github.com/eProsima/Fast-DDS/tree/master/examples/cpp/dds/SecureHelloWorldExample) (renamed to `dds_security`)

**Comment by zekai-li** [comment]
> Hi @zekai-li! 你好 ！ The list of pending changes is not public, but these are the new requirements for the examples refactor in case you want to contribute to their improvement (also you can take the following pull requests into account as a reference: #4547, #4570, #4836, #4889, #4859, #4913):待定更改的列表不是公开的，但这些是示例重构的新要求，以防您想为示例的改进做出贡献（您也可以考虑以下拉取请求作为参考： #4547 、 #4570 、 #4836 、 #4889 、 #4859 、 #4913 ）：
> 
> * remove the DDS prefix from the binaries从二进制文件中删除 DDS 前缀
> * snake case in binary names and directory names二进制名称和目录名称中的蛇形大小写
> * take all examples out of the `dds` folder从 `dds` 文件夹中取出所有示例
> * launch only one endpoint per binary (always running them in different shells)每个二进制文件仅启动一个端点（始终在不同的 shell 中运行它们）
> * unify args names and utility统一参数名称和实用程序
> * follow new Application architecture (Application, PublisherApp, SubscriberApp)...遵循新的应用程序架构（应用程序、PublisherApp、SubscriberApp）...
> * write proper README.md with the purpose of the example and expected inputs, outputs, behavior…根据示例的目的和预期的输入、输出、行为编写正确的 README.md...
> * implement listener callback in the same class (inheritance)在同一个类中实现监听器回调（继承）
> * include initialization (`init()`) methods in the constructors, and remove existing `init()` methods在构造函数中包含初始化 ( `init()` ) 方法，并删除现有的 `init()` 方法
> * improve parsing options to be a black box to the user改进解析选项，使其成为用户的黑匣子
> 
> You can start with the [RequestReplyExample](https://github.com/eProsima/Fast-DDS/tree/master/examples/cpp/dds/RequestReplyExample), which should be renamed to `request_reply`, or with the [SecureHelloWorldExample](https://github.com/eProsima/Fast-DDS/tree/master/examples/cpp/dds/SecureHelloWorldExample) (renamed to `dds_security`)您可以从 RequestReplyExample 开始，它应重命名为 `request_reply` ，或者从 SecureHelloWorldExample 开始（重命名为 `dds_security` ）

Thanks for your detailed response, I will submit the code for our community as soon as possible

**Pull request closed without merging**
