### PR TITLE
[15997] Construct with decltype when inserting to map on FlowControllerFactory

### PR DESCRIPTION
**Pull request by MiguelCompany**
## Description

This should fix building with old compilers that cannot deduce they should use the move constructor of unique_ptr.

@Mergifyio backport 2.7.x 2.6.x

## Contributor Checklist
- [x] Commit messages follow the project guidelines. 
- [x] The code follows the style guidelines of this project. 
- **N/A** Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added. 
- **N/A** Any new/modified methods have been properly documented using Doxygen. 
- [ ] Fast DDS test suite has been run locally. 
- [x] Changes are ABI compatible. 
- [x] Changes are API compatible. 
- **N/A** Documentation builds and tests pass locally. 
- **N/A** New feature has been added to the `versions.md` file (if applicable).
- **N/A** New feature has been documented/Current behavior is correctly described in the documentation. 

## Reviewer Checklist
- [x] Check contributor checklist is correct.
- [x] Check CI results: changes do not issue any warning.
- [x] Check CI results: failing tests are unrelated with the changes.

### CODE REVIEW

**Comment by MiguelCompany** [comment]
@richiprosima Please test this

**Comment by MiguelCompany** [comment]
@richiprosima Please test this

**Comment by jimlloyd** [comment]
This fixes the problem we have been having with gcc 7.2.

**Review by EduPonz — APPROVED** [review]

**Comment by MiguelCompany** [comment]
@Mergifyio backport 2.7.x 2.6.x

**Pull request merged**
