### PR TITLE
Behaviour change: historical data is not considered lost

### PR DESCRIPTION
**Pull request by richiware**
## Description

Because of #2282, several test started to fail in ROS2 CI. This is caused by a design decision: historical data is considered lost and therefore the user is warning. We decided to change this decision and start not considering historical data as lost. This PR performs the changes for that.

## Contributor Checklist
- [x] Commit messages follow the project guidelines. 
- [x] The code follows the style guidelines of this project. 
- [x] Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added. 
- [x] Any new/modified methods have been properly documented using Doxygen. 
- [x] Fast DDS test suite has been run locally. 
- [x] Changes are ABI compatible. 
- [x] Changes are API compatible. 
- [ ] Documentation builds and tests pass locally. 
- [ ] New feature has been added to the `versions.md` file (if applicable).
- [ ] New feature has been documented/Current behavior is correctly described in the documentation. 

## Reviewer Checklist
- [ ] Check contributor checklist is correct.
- [ ] Check CI results: changes do not issue any warning.
- [ ] Check CI results: failing tests are unrelated with the changes.

### CODE REVIEW

**Review by MiguelCompany — APPROVED** [review]
LGTM with green CI

**Review by MiguelCompany — APPROVED** [review]
LGTM with green CI

**Comment by Blast545** [comment]
CI jobs on ROS2 CI: 

Linux: [Build Status](https://ci.ros2.org/job/ci_linux/16799/)
Linux_aarch64: [Build Status](https://ci.ros2.org/job/ci_linux-aarch64/11377/)

**Comment by EduPonz** [comment]
> CI jobs on ROS2 CI: 
> 
> Linux: [Build Status](https://ci.ros2.org/job/ci_linux/16799/)
> Linux_aarch64: [Build Status](https://ci.ros2.org/job/ci_linux-aarch64/11377/)

It seems something is broken on the aarch64 CI during installation

**Comment by Blast545** [comment]
> It seems something is broken on the aarch64 CI during the dependencies installation

Yeah, those problems with the dependencies seem to be a phased dependency affecting Ubuntu. We saw these on some of our nightlies as well. 

`ros2topic/test/test_cli.py::test_cli` doesn't have any errors on the linux build attached, I think it's safe to assume this PR fixed the errors on `ros2topic` on our buildfarm.

**Pull request merged**
