### PR TITLE
[20236] Improve environment variable substitution algorithm

### PR DESCRIPTION
**Pull request by MiguelCompany**
## Description

Oss-fuzz issue [62868](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=62868) unveiled a performance issue in the algorithm for environment variable substitution on XML.

Along with an improvement of the algorithm so the input string is copied only once into the result, this PR avoids substitution of `${_}`, which on Linux shells is usually the full path to the executable of the application and, as such, exposing it is considered a security vulnerability.

@Mergifyio backport 2.12.x

## Contributor Checklist
- [x] Commit messages follow the project guidelines. 
- [x] The code follows the style guidelines of this project. 
- [x] Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
- **N/A** Any new/modified methods have been properly documented using Doxygen. 
- [x] Changes are ABI compatible. 
- [x] Changes are API compatible. 
- **N/A** New feature has been added to the `versions.md` file (if applicable).
- **N/A** New feature has been documented/Current behavior is correctly described in the documentation. 
    
- [x] Applicable backports have been included in the description.

## Reviewer Checklist
- [x] The PR has a milestone assigned.
- [x] The title and description correctly express the PR's purpose.
- [x] Check contributor checklist is correct.
- [x] Check CI results: changes do not issue any warning.
- [x] Check CI results: failing tests are unrelated with the changes.

### CODE REVIEW

**Comment by Mario-DL** [comment]
@richiprosima please test mac

**Review by Mario-DL — COMMENTED** [review]
Changes LGTM.
The performance of the algorithm is dramatically improved. The impact is notorious when simply executing the `XMLParserTests` regression test suite.
I ran the test without the fix `~1000` times in a Linux shell environment but I could not reproduce the regression test failure. Despite that, I think that this PR brings a nice improvement. Tempted to approve wit h Green CI

**Comment by Mario-DL** [comment]
Just for the sake of completeness. Launching the `XMLParserTests.regression` with `retest-until-fail 500` in a Linux shell I obtained:
* That `with` the fix, but commenting the `if` in line `73` (leaving the next `else if` as `if`), it takes `8.14 secs` to finish with `100% passed`.
* That `without` the fix, it takes `20.0 mints` to complete with a mean of `2.3 secs` per run and `100%` of tests passed.

**Comment by MiguelCompany** [comment]
> Just for the sake of completeness. Launching the `XMLParserTests.regression` with `retest-until-fail 500` in a Linux shell I obtained:
> 
> * That with the fix, it takes `7.30 secs` to finish with `100% passed`.
> * That `with` the fix, but commenting the `if` in line `73` (leaving the next `else if` as `if`), it takes `8.14 secs` to finish with `100% passed`.
> * That `without` the fix, it takes `20.0 mints` to complete with a mean of `2.3 secs` per run and `100%` of tests passed.

Around 150 times faster!

So, given the fact that the oss-fuzz issue was about a timeout, could we approve this?

**Review by Mario-DL — APPROVED** [review]

**Comment by Mario-DL** [comment]
@richiprosima please test mac

**Comment by Mario-DL** [comment]
@richiprosima please test mac

**Comment by Mario-DL** [comment]
@richiprosima please test mac

**Comment by Mario-DL** [comment]
@richiprosima please test mac

**Comment by EduPonz** [comment]
@Mergifyio backport 2.12.x

**Pull request merged**
