### PR TITLE
Reset the minimum time before canceling WLP timer

### PR DESCRIPTION
**Pull request by advancenOO**
min_automatic_ms_ and min_manual_by_participant_ms_ should be reset to max() before canceling the WLP timer, otherwise the WLP timer will not be restarted next time calling add_local_writer.

### CODE REVIEW

**Comment by richiware** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/3140/)
* Linux aarch64[Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux%20aarch64/358/)
* Mac [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/2803/)
* Windows [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/3172/)

**Review by MiguelCompany — CHANGES_REQUESTED** [review]
The changes LGTM, but a regression test on [this file](https://github.com/eProsima/Fast-DDS/blob/master/test/blackbox/common/BlackboxTestsLivelinessQos.cpp) would be highly appreciated.

**Comment by advancenOO** [comment]
OK, I will add a test for it this week.

**Comment by MiguelCompany** [comment]
@advancenOO Could you please fix the linter issue?

**Comment by richiware** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/3221/)
* Linux aarch64[Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux%20aarch64/432/)
* Mac [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/2885/)
* Windows [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/3253/)

**Comment by advancenOO** [comment]
Trying to fix dds-pim issues.

**Comment by richiware** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/3266/)
* Linux aarch64[Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux%20aarch64/477/)
* Mac [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/2918/)
* Windows [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/3298/)

**Comment by advancenOO** [comment]
Not sure if it is known failure.

**Comment by MiguelCompany** [comment]
> Not sure if it is known failure.

We are having some issues with the Mac CI machine. I will re-run.

**Comment by advancenOO** [comment]
OK, thanks.

**Comment by richiware** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/3271/)
* Linux aarch64[Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux%20aarch64/482/)
* Mac [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/2923/)
* Windows [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/3303/)

**Comment by MiguelCompany** [comment]
Failures seem unrelated. Merging in.

**Pull request merged**
