### PR TITLE
Fix strict realtime feature [13838]

### PR DESCRIPTION
**Pull request by richiware**
Some logical paths from user thread lose the strict realtime feature. This was caused by new features implemented. This PR adds strict realtime again.

Needs #2473 merged first.

### CODE REVIEW

**Comment by MiguelCompany** [comment]
@richiprosima Please test this

**Comment by Mario-DL** [comment]
We may be leaving this PR for the next release.

**Comment by JLBuenoLopez-eProsima** [comment]
@richiware This is being fixed in separate PRs, is not it?. Can we close this one? Thanks!

**Comment by richiware** [comment]
Sure.

**Pull request closed without merging**
