### PR TITLE
Improvements on StatefulWriter

### PR DESCRIPTION
**Pull request by IkerLuengo**
Some improvements on StatefulWriter:

* Avoid trying to send a heartbeat if no reader is matched.
Although quite harmless, this may cause an ERROR log with security because the writer is unable to encrypt the message if there are no matched readers.
* Avoid sending traffic to newly matched intraprocess reader.

### CODE REVIEW

**Review by MiguelCompany — DISMISSED** [review]

**Comment by MiguelCompany** [comment]
@IkerLuengo Would you mind doing this also on master ?

**Comment by MiguelCompany** [comment]
Also please uncrustify

**Review by MiguelCompany — APPROVED** [review]

**Comment by richiware** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/2783/)
* Linux aarch64[Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux%20aarch64/137/)
* Mac [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/2558/)
* Windows [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/2795/)

**Comment by richiware** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/2808/)
* Linux aarch64[Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux%20aarch64/153/)
* Mac [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/2578/)
* Windows [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/2820/)

**Review by MiguelCompany — APPROVED** [review]
LGTM

**Comment by richiware** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/2811/)
* Linux aarch64[Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux%20aarch64/156/)
* Mac [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/2581/)
* Windows [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/2823/)

**Comment by MiguelCompany** [comment]
Failures seem unrelated. Going in.

**Pull request merged**
