### PR TITLE
Enable SHM as a default transport <1.10.x>

### PR DESCRIPTION
**Pull request by MiguelCompany**

### CODE REVIEW

**Comment by richiware** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/2029/)
* Mac [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/1773/)
* Windows [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/2023/)

**Comment by richiware** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/2032/)
* Mac [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/1783/)
* Windows [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/2026/)

**Comment by adolfomarver** [comment]
@MiguelCompany Threre are some valgrind errors in two SHM tests, but those two tests make things like killing processes, so I think is ok.

**Comment by MiguelCompany** [comment]
> @MiguelCompany Threre are some valgrind errors in two SHM tests, but those two tests make things like killing processes, so I think is ok.

I have marked this as ready, but will not merge until ROS2 changes to 2.0.x or confirms this change is not harmful for them.

**Comment by MiguelCompany** [comment]
Closing, as we are dropping support for 1.10.x

**Pull request closed without merging**
