### PR TITLE
Check if not null before calling delete.

### PR DESCRIPTION
**Pull request by fujitatomoya**
general code improvement with null check before delete.

Signed-off-by: Tomoya.Fujita <Tomoya.Fujita@sony.com>

## Description

If these objects are not create as expected when it fails to create entity successfully, this will lead to segmentation fault.

## Contributor Checklist

- [ ] Commit messages follow the project guidelines. 
- [ ] The code follows the style guidelines of this project. 
- [ ] Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added. 
- [ ] Any new/modified methods have been properly documented using Doxygen. 
- [ ] Fast DDS test suite has been run locally. 
- [x] Changes are ABI compatible. 
- [x] Changes are API compatible. 
- [ ] Documentation builds and tests pass locally. 
- [ ] New feature has been added to the `versions.md` file (if applicable).
- [ ] New feature has been documented/Current behavior is correctly described in the documentation. 

## Reviewer Checklist

- [ ] Check contributor checklist is correct.
- [ ] Check CI results: changes do not issue any warning.
- [ ] Check CI results: failing tests are unrelated with the changes.

### CODE REVIEW

**Comment by fujitatomoya** [comment]
found this minor fix during https://github.com/eProsima/Fast-DDS/issues/3056

**Comment by fujitatomoya** [comment]
friendly ping, we detected this core crash with this stack trace.

**Comment by EduPonz** [comment]
Hi @fujitatomoya ,

I think we are OK with the change, but we are wondering why is it necessary. According to the [delete expression article in cppreference](https://en.cppreference.com/w/cpp/language/delete), it should be OK to call delete on `nullptr`:

* For the first (non-array) form, expression must be a pointer to an object type or a class type [contextually implicitly convertible](https://en.cppreference.com/w/cpp/language/implicit_conversion) to such pointer, and its value must be either null or pointer to a non-array object created by a [new-expression](https://en.cppreference.com/w/cpp/language/new), or a pointer to a base subobject of a non-array object created by a [new-expression](https://en.cppreference.com/w/cpp/language/new).

I guess that this could become a problem when redefining the behaviour of `delete` with some other implementation. Can that be what you are doing?

**Comment by fujitatomoya** [comment]
> it should be OK to call delete on nullptr:

this is no problem, but i am suggesting to store the nullptr after delete here. calling `delete` on already deleted object will go undefined behavior and mostly crash. it does not make sense to store nullptr here? i am not sure if this sequence is considered. we just detected that stack trace that show delete the deleted object, so this is just a suggested fix.

if you do not want to `if` statement to check nullptr, that makes sense to me. and i can do that.

thanks,

**Comment by MiguelCompany** [comment]
@fujitatomoya You are right. But then the root cause is that `DataWriterImpl` or `DataReaderImpl` are being destructed twice... We'd then need to find why that is happening, and add a fix for it along with the already proposed changes.

**Comment by fujitatomoya** [comment]
> But then the root cause is that DataWriterImpl or DataReaderImpl are being destructed twice...

precisely correct !

> We'd then need to find why that is happening, and add a fix for it along with the already proposed changes.

yeah, that is no problem. just checking, no pressure.

**Comment by fujitatomoya** [comment]
@MiguelCompany @EduPonz it is all up to you guys if taking this or not. if not, please go ahead to close this PR 👍

**Pull request closed without merging**
