### PR TITLE
Fixed docu typos

### PR DESCRIPTION
**Pull request by jwillemsen**
Signed-off-by: Johnny Willemsen <jwillemsen@remedy.nl>

### CODE REVIEW

**Comment by EduPonz** [comment]
Thanks @jwillemsen for your numerous contributions!
I've marked the PR with `no-test` label so CI doesn't run for non-code related changes.

**Comment by jwillemsen** [comment]
Ready with these changes for today ;-)

**Comment by jwillemsen** [comment]
Nothing to add to this PR, feel free to merge

**Comment by jwillemsen** [comment]
Anything I need to add to this PR? Looks the uncrustify had a setup issue

**Comment by MiguelCompany** [comment]
Thank you @jwillemsen for your contribution!

**Pull request merged**
