### PR TITLE
Allow setting complex value of non-container type

### PR DESCRIPTION
**Pull request by YangboLong**
Signed-off-by: Yangbo Long <yangbo.long.mav@gmail.com>

### CODE REVIEW

**Review by MiguelCompany — CHANGES_REQUESTED** [review]
Would you mind adding a regression test on `test/unittest/xtypes/XTypesTests.cpp` ?

**Comment by YangboLong** [comment]
> Would you mind adding a regression test on `test/unittest/xtypes/XTypesTests.cpp` ?

I've added some test cases. Would you please review again? @MiguelCompany

**Comment by MiguelCompany** [comment]
@YangboLong It seems this has conflicts. Would you mind doing a rebase?

**Comment by YangboLong** [comment]
@MiguelCompany I have done it.

**Review by MiguelCompany — APPROVED** [review]

**Comment by MiguelCompany** [comment]
@richiprosima Please test this

**Review by MiguelCompany — CHANGES_REQUESTED** [review]
@YangboLong
* Fix warnings on Windows
* New test is failing on Mac

**Comment by YangboLong** [comment]
@MiguelCompany I fixed the warnings on Windows last time. The Mac failure might be related to deallocation of DynamicData?

**Comment by JLBuenoLopez-eProsima** [comment]
Thanks @YangboLong for your contribution and sorry for the late reply. I am going to proceed and close this issue because right now, efforts to improve support for XTYPES v1.3 are being made (#3392) which supersedes this PR.

**Pull request closed without merging**
