### PR TITLE
2.5.0 [13323]

### PR DESCRIPTION
**Pull request by MiguelCompany**
Get ready for v2.5.0:

* Update fastcdr submodule
* Update versions.md
* Enable mirror from master to 2.5.x

### CODE REVIEW

**Review by JLBuenoLopez-eProsima — APPROVED** [review]
LGTM

**Comment by JLBuenoLopez-eProsima** [comment]
Maybe we can add in this PR the PKCS#11 feature to the `versions.md` file.

**Comment by MiguelCompany** [comment]
> Maybe we can add in this PR the PKCS#11 feature to the `versions.md` file.

Done

**Review by JLBuenoLopez-eProsima — APPROVED** [review]
:+1:

**Review by EduPonz — APPROVED** [review]

**Pull request merged**
