### PR TITLE
Added flaky tests in XFAIL_DDS_PIM test lists

### PR DESCRIPTION
**Pull request by rsanchez15**
Signed-off-by: RaulSanchez <raul@eprosima.com>

### CODE REVIEW

**Review by EduPonz — APPROVED** [review]
LGTM

**Comment by EduPonz** [comment]
@MiguelCompany , what do you think?

**Review by MiguelCompany — APPROVED** [review]
👍

**Comment by richiware** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/3399/)
* Linux aarch64[Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux%20aarch64/595/)
* Mac [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/3047/)
* Windows [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/3431/)

**Pull request merged**
