### PR TITLE
[15600] Correct initialization order warning in DomainParticipantImpl mock

### PR DESCRIPTION
**Pull request by EduPonz**
Signed-off-by: Eduardo Ponz <eduardoponz@eprosima.com>

## Description

This PRs corrects an initialization order warning in DomainParticipantImpl

## Contributor Checklist
- [x] Commit messages follow the project guidelines. 
- [x] The code follows the style guidelines of this project. 
- *N/A* Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added. 
- *N/A* Any new/modified methods have been properly documented using Doxygen. 
- [ ] Fast DDS test suite has been run locally. 
- [x] Changes are ABI compatible. 
- [x] Changes are API compatible. 
- *N/A* Documentation builds and tests pass locally. 
- *N/A* New feature has been added to the `versions.md` file (if applicable).
- *N/A* New feature has been documented/Current behavior is correctly described in the documentation. 

## Reviewer Checklist
- [ ] Check contributor checklist is correct.
- [ ] Check CI results: changes do not issue any warning.
- [ ] Check CI results: failing tests are unrelated with the changes.

### CODE REVIEW

**Review by jsantiago-eProsima — APPROVED** [review]
LGTM

**Comment by EduPonz** [comment]
@richiprosima please test windows

**Comment by MiguelCompany** [comment]
@mergifyio rebase

**Comment by MiguelCompany** [comment]
@richiprosima Please test this

**Review by MiguelCompany — APPROVED** [review]

**Pull request merged**
