### PR TITLE
Refs #9037 Extend TopicDataType API [9041]

### PR DESCRIPTION
**Pull request by LuisGP**
- Add virtual method `is_bounded` returning `false` by default
- Add virtual method `is_plain` returning `false` by default

### CODE REVIEW

**Comment by richiware** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/2486/)
* Mac [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Mac/2300/)
* Windows [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/2493/)

**Review by MiguelCompany — CHANGES_REQUESTED** [review]
Instead of bumping version, I would prefer to have a feature `#define`.

**Comment by richiware** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/2931/)
* Linux aarch64[Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux%20aarch64/210/)
* Mac Build Status
* Windows [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/2942/)

**Comment by richiware** [comment]
Build status:
* Linux [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Linux/2936/)
* Linux aarch64Build Status
* Mac Build Status
* Windows [Build Status](http://jenkins.eprosima.com:8080/job/FastRTPS%20Manual%20Windows/2948/)

**Comment by IkerLuengo** [comment]
@MiguelCompany does this PR need anything else before merging?

**Review by MiguelCompany — APPROVED** [review]

**Pull request merged**
