### PR TITLE
Avoid using a custom atomic type for shared pointer data.

### PR DESCRIPTION
**Pull request by mp3guy**
Running [MSAN](https://github.com/google/sanitizers/wiki/MemorySanitizer) on a trivial example results in an instant crash and cryptic stack trace from a debugger:

```
Program received signal SIGSEGV, Segmentation fault.
0x00000000020aa99f in select_compare_exchange_16 () at third-party/gcc/src/libatomic/cas_n16.c:124
124	third-party/gcc/src/libatomic/cas_n16.c: No such file or directory.
(gdb) bt
#0  0x00000000020aa99f in select_compare_exchange_16 () at third-party/gcc/src/libatomic/cas_n16.c:124
#1  0x00007ffff7de04a8 in _dl_relocate_object () from /lib64/ld-linux-x86-64.so.2
#2  0x00007ffff7dd8208 in dl_main () from /lib64/ld-linux-x86-64.so.2
#3  0x00007ffff7dee14f in _dl_sysdep_start () from /lib64/ld-linux-x86-64.so.2
#4  0x00007ffff7dd6136 in _dl_start () from /lib64/ld-linux-x86-64.so.2
#5  0x00007ffff7dd5088 in _start () from /lib64/ld-linux-x86-64.so.2
#6  0x0000000000000001 in ?? ()
#7  0x00007fffffffe0f1 in ?? ()
#8  0x0000000000000000 in ?? ()
```

We narrowed it down to the fact a custom type is being used in a `std::atomic` that is shared between processes. [This question and answer](https://www.quora.com/Can-C++11-std-atomic_*-be-used-across-processes-via-shared-memory) seems to say this is not guaranteed to work, and sure enough, this fix makes the memory sanitizer happy.

### CODE REVIEW

**Review by MiguelCompany — APPROVED** [review]
The changes look good to me. We have an issue with the CI infrastructure, so I will mark this as ready, and will merge after CI has been run

**Comment by MiguelCompany** [comment]
@richiprosima Please test this

**Review by MiguelCompany — CHANGES_REQUESTED** [review]
@mp3guy Please fix [linter errors](http://jenkins.eprosima.com:8080/job/fastdds_github_uncrustify/2009/)

**Comment by mp3guy** [comment]
Sure thing! That link doesn't work for me right now, is there a way I can run the linter locally?

**Comment by EduPonz** [comment]
Hi @mp3guy ,

> Sure thing! That link doesn't work for me right now, is there a way I can run the linter locally?

Sure! we use uncrustify, the config file for it is hosted [here](https://github.com/eProsima/cpp-style/blob/master/uncrustify.cfg)

**Comment by mp3guy** [comment]
Thanks, should be good now.

**Review by MiguelCompany — CHANGES_REQUESTED** [review]
Please fix [build errors](http://jenkins.eprosima.com:8080/job/fastdds_linux/135/gcc/)

**Comment by mp3guy** [comment]
Huh weird, I couldn't repro those build errors locally. Should be addressed now.

**Review by MiguelCompany — DISMISSED** [review]
LGTM with green CI.

**Review by MiguelCompany — APPROVED** [review]
LGTM.

All platforms built correctly without warnings.
Failed tests are known to be flaky.

**Comment by MiguelCompany** [comment]
Going in. Thank you @mp3guy !

**Pull request merged**
