### PR TITLE
[12371] Waitset implementation

### PR DESCRIPTION
**Pull request by MiguelCompany**
Add WaitSet, GuardCondition, and StatusCondition implementation and tests.

Documentation PR: eProsima/Fast-DDS-docs#279

### CODE REVIEW

**Comment by MiguelCompany** [comment]
@richiprosima Please test windows

**Comment by IkerLuengo** [comment]
@richiprosima Please test linux

**Review by IkerLuengo — CHANGES_REQUESTED** [review]
`Entity::get_statuscondition()` is returning a const reference. We should be returning a non-const reference so that we can apply modifications, like `StatusCondition::set_enabled_statuses()`, which is a mutator method. Although `Condition` itself has no mutating methods, we cannot assume that its derivatives have none.

This was found during the review of the examples in the documentation

**Comment by MiguelCompany** [comment]
> `Entity::get_statuscondition()` is returning a const reference. We should be returning a non-const reference so that we can apply modifications, like `StatusCondition::set_enabled_statuses()`, which is a mutator method. Although `Condition` itself has no mutating methods, we cannot assume that its derivatives have none.
> 
> This was found during the review of the examples in the documentation
> 
> And while we are at it, we could also remove the logWarning stating that `get_statuscondition` is not implemented

This is part of the changes .... Were you looking at the code in `master`, perhaps?

**Review by IkerLuengo — APPROVED** [review]
> This is part of the changes .... Were you looking at the code in `master`, perhaps?

Sincerely, I do not know what I was looking 😥

**Pull request merged**
