### PR TITLE
Environment file feature

### PR DESCRIPTION
**Pull request by MiguelCompany**

### CODE REVIEW

**Comment by MiguelCompany** [comment]
@richiprosima Please test mac

**Review by EduPonz — DISMISSED** [review]
LGTM with green CI 🚀

**Comment by MiguelCompany** [comment]
@richiprosima Please test aarch64

**Comment by MiguelCompany** [comment]
@EduPonz I have rebased this and added a commit to fix `StatisticsDataWriterQosTest`, which was not updated on #2176 and #2180.

**Review by EduPonz — CHANGES_REQUESTED** [review]
Last changes look good to me, although uncrustify would need to be fixed

**Comment by MiguelCompany** [comment]
Uncrustify failed on a third-party file. That's not an error, is it?

**Review by EduPonz — APPROVED** [review]
LGTM

**Comment by EduPonz** [comment]
All failures are unrelated to this PR, so I'll go ahead and merge it

**Pull request merged**
