### PR TITLE
[20653] Increase sleep to miss the deadline in macOS flaky tests

### PR DESCRIPTION
**Pull request by elianalf**
## Description

This PR increases the sleep between samples sent to miss the deadline in ownership flaky tests " exclusive_kind_non_keyed_reliable_deadline"

 @Mergifyio backport 2.13.x 2.10.x 

## Contributor Checklist
- [x] Commit messages follow the project guidelines. 
- [x] The code follows the style guidelines of this project. 
- N/A Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
- N/A Any new/modified methods have been properly documented using Doxygen. 
- [x] Changes are ABI compatible. 
- [x] Changes are API compatible. 
- N/A New feature has been added to the `versions.md` file (if applicable).
- N/A New feature has been documented/Current behavior is correctly described in the documentation. 
    
- [x] Applicable backports have been included in the description.

## Reviewer Checklist
- [x] The PR has a milestone assigned.
- [x] The title and description correctly express the PR's purpose.
- [x] Check contributor checklist is correct.
- [x] Check CI results: changes do not issue any warning.
- [x] Check CI results: failing tests are unrelated with the changes.

### CODE REVIEW

**Comment by elianalf** [comment]
@richiprosima please test this

**Comment by elianalf** [comment]
MAC CI passed once [here](https://github.com/eProsima/Fast-DDS/actions/runs/8568525931)

**Comment by elianalf** [comment]
@richiprosima please test this

**Review by JesusPoderoso — APPROVED** [review]
LGTM with Jenkins green CI

**Comment by elianalf** [comment]
@richiprosima please test mac

**Comment by EduPonz** [comment]
@Mergifyio backport 2.13.x 2.10.x

**Pull request merged**
