### PR TITLE
[20708] Make NetworkConfiguration private

### PR DESCRIPTION
**Pull request by JesusPoderoso**
## Description
This PR makes NetworkConfiguration private

## Contributor Checklist

- [x] Commit messages follow the project guidelines. 
- [x] The code follows the style guidelines of this project. 
- _N/A_ Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
- _N/A_ Any new/modified methods have been properly documented using Doxygen. 
- _N/A_ Any new configuration API has an equivalent XML API (with the corresponding XSD extension) 
- [x] Changes are ABI compatible. 
- [x] Changes are API compatible. 
- _N/A_ New feature has been added to the `versions.md` file (if applicable).
- _N/A_ New feature has been documented/Current behavior is correctly described in the documentation. 
    
- _N/A_ Applicable backports have been included in the description.

## Reviewer Checklist

- [x] The PR has a milestone assigned.
- [x] The title and description correctly express the PR's purpose.
- [x] Check contributor checklist is correct.
- [x] Check CI results: changes do not issue any warning.
- [x] Check CI results: failing tests are unrelated with the changes.

### CODE REVIEW

**Comment by elianalf** [comment]
@richiprosima please test_3 this

**Review by elianalf — APPROVED** [review]

**Comment by elianalf** [comment]
@richiprosima please test_3 mac

**Comment by JesusPoderoso** [comment]
@richiprosima please test_3 this

**Review by elianalf — APPROVED** [review]

**Comment by elianalf** [comment]
@richiprosima please test_3 this

**Review by elianalf — APPROVED** [review]

**Comment by elianalf** [comment]
@richiprosima please test_3 linux

**Pull request merged**
