### PR TITLE
[16192] fix notification lost

### PR DESCRIPTION
**Pull request by iuhilnehc-ynos**
Signed-off-by: Chen Lihui <lihui.chen@sony.com>

## Description

Please refer to https://github.com/ros2/rclcpp/issues/2039#issuecomment-1310024990.

## Contributor Checklist
- [ ] Commit messages follow the project guidelines. 
- [ ] The code follows the style guidelines of this project. 
- [ ] Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added. 
- [ ] Any new/modified methods have been properly documented using Doxygen. 
- [x] Fast DDS test suite has been run locally. 
- [x] Changes are ABI compatible. 
- [x] Changes are API compatible. 
- [ ] Documentation builds and tests pass locally. 
- [ ] New feature has been added to the `versions.md` file (if applicable).
- [ ] New feature has been documented/Current behavior is correctly described in the documentation. 

## Reviewer Checklist
- [ ] Check contributor checklist is correct.
- [ ] Check CI results: changes do not issue any warning.
- [ ] Check CI results: failing tests are unrelated with the changes.

### CODE REVIEW

**Review by fujitatomoya — APPROVED** [review]
this looks good to me.

**Comment by MiguelCompany** [comment]
@iuhilnehc-ynos Thank you for your contribution. Changes LGTM, but we'll need to add a regression test before merging this.

**Comment by iuhilnehc-ynos** [comment]
@MiguelCompany @fujitatomoya 

I tried my best to add a regression test. The test log shows that I need 176070(a random number) times to run the test to output an error in my local machine if not applying [the patch](https://github.com/eProsima/Fast-DDS/pull/3087/commits/744524ae73cb3a6ae3af902228787721c56ec785). 

```
[16:25:12 OptiPlex-7080] /home/chenlh/Projects/ROS2/eProsima/build/fastrtps/test/unittest/dds/core/condition  
chenlh condition $ mytest ./WaitSetImplTests --gtest_filter="*fix_wait_notification_lost"

...

Times 176070
Note: Google Test filter = *fix_wait_notification_lost
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from WaitSetImplTests
[ RUN      ] WaitSetImplTests.fix_wait_notification_lost
/home/chenlh/Projects/ROS2/eProsima/src/fastrtps/test/unittest/dds/core/condition/WaitSetImplTests.cpp:232: Failure
Expected equality of these values:
  ReturnCode_t::RETCODE_OK
    Which is: 0
  ret
    Which is: 4-byte object <01-00 00-00>
terminate called without an active exception

```

Do you have any suggestions about the regression test?

**Comment by fujitatomoya** [comment]
@iuhilnehc-ynos 

> Do you have any suggestions about the regression test?

not really, sorry 😢

**Comment by MiguelCompany** [comment]
@richiprosima Please test this

**Comment by MiguelCompany** [comment]
@iuhilnehc-ynos It seems this PR is introducing possible deadlocks. At least that is what the TSan job is complaining about. You can get the report from [here](https://github.com/eProsima/Fast-DDS/suites/9330068872/artifacts/438692332).

**Comment by MiguelCompany** [comment]
@iuhilnehc-ynos I think I fixed the deadlock on 8c6036436161319128ef005964e4446f52512ad9. Let's wait for the TSan job.

**Comment by MiguelCompany** [comment]
@richiprosima Please test this

**Comment by MiguelCompany** [comment]
@MiguelBarro This has a deadlock report on code related with ReadConditions. Would you mind taking a look?

**Comment by MiguelBarro** [comment]
The fix consists on assuring no notification will take place on predicate evaluation by taken the mutex during notifications (`WaitSetImpl::wake_up`) changes.
Unfortunately, that introduces an ABBA deadlock on intraproccess scenarios:
Waiting thread:
+ A waitset mutex (wait())
+ B reader mutex (retrieving trigger value)
Writing thread:
+ B  reader mutex (`StatefulReader::processDataMsg` directly called from writer)
+ A waitset mutex (notification to the Conditions implies wakeup)
A workaround may be to introduce an `atomic_bool` flag in the `WaitSetImpl`. This will be set to true on wake up avoding taking the mutex. The wait predicate must check the flag and decide to reevaluate.
Another alternative is avoid taking the reader mutex on Condition notification (there is a devoted mutex for the condition collection). The issue here is that the reader mutex is recursive and taken upstream in the stack which makes it a costly refactor.
Surely I came up with a better solution on the weekend.

**Comment by fujitatomoya** [comment]
@MiguelCompany @MiguelBarro anything we need to do on our side? friendly ping.

**Comment by fujitatomoya** [comment]
friendly ping, this can resolve a couple of issues.

**Comment by MiguelCompany** [comment]
@richiprosima Please test this

**Comment by MiguelCompany** [comment]
@mergifyio backport 2.8.x 2.7.x 2.6.x

**Comment by iuhilnehc-ynos** [comment]
I am sorry about the comment https://github.com/ros2/rmw_fastrtps/issues/650#issuecomment-1360664718.
I just tested with commit https://github.com/eProsima/Fast-DDS/pull/3087/commits/8c6036436161319128ef005964e4446f52512ad9 before.

If using https://github.com/eProsima/Fast-DDS/pull/3087/commits/34a8f8d57f8e24135c35eeb9965b03f2010c3022, the `wait forever` issue in https://github.com/ros2/rmw_fastrtps/issues/650 still exists.

**Comment by MiguelCompany** [comment]
@iuhilnehc-ynos Thank you for checking with 34a8f8d57f8e24135c35eeb9965b03f2010c3022.

We will then update this PR to aa260da77dd827dc13841dc9573cc5448cfe14b9 and close #3098.

Would you mind checking ros2/rmw_fastrtps#650 with aa260da77dd827dc13841dc9573cc5448cfe14b9 to verify it solves the issue?

**Comment by MiguelCompany** [comment]
@richiprosima Please test this

**Comment by MiguelCompany** [comment]
@richiprosima Please test Linux

**Comment by iuhilnehc-ynos** [comment]
> Would you mind checking [ros2/rmw_fastrtps#650](https://github.com/ros2/rmw_fastrtps/issues/650) with [aa260da](https://github.com/eProsima/Fast-DDS/commit/aa260da77dd827dc13841dc9573cc5448cfe14b9) to verify it solves the issue?

I believe this PR can fix the `wait forever` issus, but it leads to another issue as belows

```
[INFO] [1672971861.484102416] [sender]: Sending tick: '6357'...              // timer period is set with 10ms
[INFO] [1672971861.493948311] [sender]: Sending tick: '6358'...
[INFO] [1672971861.504098546] [sender]: Sending tick: '6359'...
[INFO] [1672971861.513917624] [sender]: Sending tick: '6360'...
[INFO] [1672971861.523958969] [sender]: Sending tick: '6361'...
[INFO] [1672971861.533877038] [sender]: Sending tick: '6362'...
[INFO] [1672971862.034249728] [sender]: Sending tick: '6363'...             // it cost about 500ms to trigger the next timer callback.
```

**Comment by MiguelCompany** [comment]
@iuhilnehc-ynos The browser showed me your commit after merging. We're reverting the merge on #3193.

I thought about this a bit more during the weekend, and decided a new approach, based on your original solution.

After the revert is done, I will create a new PR with the changes on [this branch](https://github.com/eProsima/Fast-DDS/tree/bugfix/16192). Could you check aginst that branch?

**Comment by iuhilnehc-ynos** [comment]
> After the revert is done, I will create a new PR with the changes on [this branch](https://github.com/eProsima/Fast-DDS/tree/bugfix/16192). Could you check aginst that branch?

It seems there is some compilation issue on that branch. Maybe you are working on it, I'll check it based on your new PR.

**Comment by MiguelCompany** [comment]
> It seems there is some compilation issue on that branch. Maybe you are working on it, I'll check it based on your new PR.

@iuhilnehc-ynos Yeah, sorry about that. It should be fixed now. I have also created #3195 with the backport to 2.6.x, so we can have the fix on Humble too.

**Pull request merged**
