### PR TITLE
Fix: mac address overflow on windows

### LINKED ISSUE #3982: Mac address overflow in IPFinder::getAllMACAddress() on Windows
### Is there an already existing issue for this?

- [X] I have searched the existing issues

### Expected behavior

`IPFinder::getAllMACAddress()` works well as designed.

### Current behavior

`IPFinder::getAllMACAddress()` crash with debugger exception:
`Run-Time Check Failure #2 - Stack around the variable 'mac' was corrupted.`

### Steps to reproduce

Run following code on Windows platform having network adaptor "Microsoft Teredo Tunneling Adapter":
```cpp
DomainParticipantQos pqos;
pqos.name("Participant_sub");
participant_ = DomainParticipantFactory::get_instance()->create_participant(0, pqos);
```

### Fast DDS version/commit

All versions since `v2.6.6` up to `master`, older versions not checked yet.

### Platform/Architecture

Windows 10 Visual Studio 2019

### Transport layer

Default configuration, UDPv4 & SHM

### Additional context

This bug happend on

https://github.com/eProsima/Fast-DDS/blob/16e7d9058b62d2a5d19f49abebbb04e91a8e9d75/src/cpp/utils/IPFinder.cpp#L268

, where `mac.address` has length of 6 at 

https://github.com/eProsima/Fast-DDS/blob/16e7d9058b62d2a5d19f49abebbb04e91a8e9d75/include/fastrtps/utils/IPFinder.h#L68

, but `IP_ADAPTER_ADDRESSES::PhysicalAddress` has length up to `MAX_ADAPTER_ADDRESS_LENGTH`, which is 8.

In some situation, such as adaptor with `IP_ADAPTER_ADDRESSES::Description = "Microsoft Teredo Tunneling Adapter"`, Windows reports `IP_ADAPTER_ADDRESSES::PhysicalAddressLength = 8` here.

All 8 bytes of `IP_ADAPTER_ADDRESSES::PhysicalAddress` are `0` in this situation, so use minimal length 6 does not affect the result.

### XML configuration file

Default configuration.

### Relevant log output

No other log.

### Network traffic capture

No network traffic at the point.

### PR DESCRIPTION
**Pull request by ZgblKylin**
## Description

This pull request fixed #3982: Mac address overflow in `IPFinder::getAllMACAddress()` on Windows.

`IP_ADAPTER_ADDRESSES::PhysicalAddressLength` will get max up to 8 bytes, but we have only 6 bytes for mac address.

In some case, `GetAdaptersAddresses()` will report address with `PhysicalAddressLength=8`, e.g. "Microsoft Teredo Tunneling Adapter", which will cause crash at `DomainParticipantFactory::create_participant()`. All 8 bytes of `IP_ADAPTER_ADDRESSES::PhysicalAddress` here are `0` in this situation, so use minimal length 6 does not affect the result.

This bug fix could be backported to older versions.

This fix is valid for all versions since `v2.6.6` up to `master`, older versions not checked yet. It should be merged to all branches having `IPFinder::getAllMACAddress()`.

## Contributor Checklist
- [X] Commit messages follow the project guidelines. 
- [X] The code follows the style guidelines of this project. 
- [X] Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
- [X] Any new/modified methods have been properly documented using Doxygen. 
- [X] Changes are ABI compatible. 
- [X] Changes are API compatible. 
- [ ] ~~New feature has been added to the `versions.md` file (if applicable).~~
  - No new feature added.
- [ ] ~~New feature has been documented/Current behavior is correctly described in the documentation.~~ 
    
  - No new feature added.
- [X] Applicable backports have been included in the description.

## Reviewer Checklist
- [x] The PR has a milestone assigned.
- [x] Check contributor checklist is correct.
- [ ] Check CI results: changes do not issue any warning.
- [ ] Check CI results: failing tests are unrelated with the changes.

### CODE REVIEW

**Comment by ZgblKylin** [comment]
Sorry for force-pushes, DCO and gpg sign are signed correctly now, no more push needed.

**Comment by ZgblKylin** [comment]
Update description, adding line:
> All 8 bytes of `IP_ADAPTER_ADDRESSES::PhysicalAddress` are `0`, so use minimal length 6 does not affect the result.

**Review by MiguelCompany — APPROVED** [review]

**Comment by MiguelCompany** [comment]
@mergifyio backport 2.11.x 2.10.x 2.6.x

**Comment by MiguelCompany** [comment]
@richiprosima Please test this

**Comment by MiguelCompany** [comment]
@richiprosima Please test windows

**Pull request merged**
