### PR TITLE
[10173] Use absolute paths when loading XML files

### PR DESCRIPTION
**Pull request by Mario-DL**
## Description

This PR forwards a refactor from the work in #1657 to `master`.
In addition, it solves a name collision error with the variable name `INTERFACE`. When importing `windows.h` a `2275 error : illegal use of this type as an expression` was  caused

@Mergifyio backport 2.14.x 2.13.x 2.10.x 2.6.x

## Contributor Checklist

- [X] Commit messages follow the project guidelines. 
- [X] The code follows the style guidelines of this project. 
- [X] Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
- [X] Any new/modified methods have been properly documented using Doxygen. 
- _N/A_ Any new configuration API has an equivalent XML API (with the corresponding XSD extension) 
- [X] Changes are ABI compatible. 
- [X] Changes are API compatible. 
- _N/A_ New feature has been added to the `versions.md` file (if applicable).
- _N/A_ New feature has been documented/Current behavior is correctly described in the documentation. 
    
- [X] Applicable backports have been included in the description.

## Reviewer Checklist

- [x] The PR has a milestone assigned.
- [x] The title and description correctly express the PR's purpose.
- [x] Check contributor checklist is correct.
- [x] Check CI results: changes do not issue any warning.
- [x] Check CI results: failing tests are unrelated with the changes.

### CODE REVIEW

**Comment by Mario-DL** [comment]
@richiprosima please test_3 this

**Comment by elianalf** [comment]
@richiprosima please test_3 this

**Comment by Mario-DL** [comment]
@richiprosima please test_3 this

**Review by JesusPoderoso — APPROVED** [review]
LGTM with green CI

**Comment by EduPonz** [comment]
@Mergifyio backport 2.14.x 2.13.x 2.10.x 2.6.x

**Pull request merged**
