### PR TITLE
[18966] Refactor of regenerate_port.

### PR DESCRIPTION
**Pull request by jsantiago-eProsima**
## Description

Small refactor to the way SHM ports are regenerated preventing extra shared pointers from being created.

## Contributor Checklist
- [x] Commit messages follow the project guidelines. 
- [x] The code follows the style guidelines of this project. 
- [NA] Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
- [NA] Any new/modified methods have been properly documented using Doxygen. 
- [x] Changes are ABI compatible. 
- [x] Changes are API compatible. 
- [NA] New feature has been added to the `versions.md` file (if applicable).
- [NA] New feature has been documented/Current behavior is correctly described in the documentation. 
    
- [x] Applicable backports have been included in the description.

## Reviewer Checklist
- [x] The PR has a milestone assigned.
- [x] Check contributor checklist is correct.
- [x] Check CI results: changes do not issue any warning.
- [x] Check CI results: failing tests are unrelated with the changes.

### CODE REVIEW

**Comment by jsantiago-eProsima** [comment]
@richiprosima please test mac

**Comment by jsantiago-eProsima** [comment]
@richiprosima please test windows

**Comment by jsantiago-eProsima** [comment]
Successful Mac test [here](http://jenkins.eprosima.com:8080/job/fastdds_mac/3706/)

**Comment by jsantiago-eProsima** [comment]
@mergifyio backport 2.6.x 2.9.x 2.10.x

**Comment by jsantiago-eProsima** [comment]
@richiprosima please test windows

**Review by JLBuenoLopez-eProsima — APPROVED** [review]
LGTM

**Pull request merged**
