### PR TITLE
[20652] Fix test filtering in CMake files

### PR DESCRIPTION
**Pull request by MiguelCompany**
## Description

This is a rework of #4603 for old branches where we are not using `gtest_discover_tests()`.
Some commits have been directly cherry-picked, while others have been reworked.
The main difference is that here we are _**ignoring**_ tests and thus the logic is _positive_ (i.e. we `IGNORE foo bar`) while in master we are _**filtering**_ them and thus the logic is _negative_ (i.e. we `TEST_FILTER -foo:bar`)

@Mergifyio backport 2.6.x

## Contributor Checklist
- [x] Commit messages follow the project guidelines. 
- *N/A* The code follows the style guidelines of this project. 
- *N/A* Tests that thoroughly check the new feature have been added/Regression tests checking the bug and its fix have been added; the added tests pass locally 
- *N/A* Any new/modified methods have been properly documented using Doxygen. 
- [x] Changes are ABI compatible. 
- [x] Changes are API compatible. 
- *N/A* New feature has been added to the `versions.md` file (if applicable).
- *N/A* New feature has been documented/Current behavior is correctly described in the documentation. 
    
- [x] Applicable backports have been included in the description.

## Reviewer Checklist
- [ ] The PR has a milestone assigned.
- [ ] The title and description correctly express the PR's purpose.
- [ ] Check contributor checklist is correct.
- [ ] Check CI results: changes do not issue any warning.
- [ ] Check CI results: failing tests are unrelated with the changes.

### CODE REVIEW

**Comment by MiguelCompany** [comment]
@richiprosima Please test this

**Review by elianalf — APPROVED** [review]

**Comment by MiguelCompany** [comment]
@mergifyio rebase

**Comment by MiguelCompany** [comment]
@richiprosima please test this

**Comment by MiguelCompany** [comment]
@Mergifyio backport 2.6.x

**Comment by MiguelCompany** [comment]
@richiprosima Please test mac

**Comment by MiguelCompany** [comment]
@richiprosima Please test mac

**Comment by MiguelCompany** [comment]
@richiprosima Please test mac

**Comment by MiguelCompany** [comment]
@richiprosima Please test mac

**Pull request merged**
